debug: Do not log any debug message unless it matches some tag
semgrep/semgrep pull request #10076
Opened 2024-04-10 09:49 UTC by IagoAbal

If no debug tags are specified, we print nothing. We don't want --debug output to be enourmous, that tends not to be useful. You should instead first consider what exact debug info you need (i.e. what "tags"). This is also a perf problem for the Python CLI that captures all this output in-memory (despite it shouldn't do that in the first place...).

test plan:
Run semgrep-core with --debug

2024-04-10 17:46 UTC, amchiclet approved these changes
Maybe add "Fixes #10044" in the PR description so that issue gets linked to this PR too.

(Or maybe the fact that I just wrote a comment here triggers that already.)

EDIT: yes, this comment made the link to that issue happen, so I guess no need to do anything on your side.

2024-04-10 20:54 UTC, mjambon requested changes
1. What should we tell the user when we need them to provide detailed logs?
2. This brings up the question: how to specify log tags?
3. And then: what tags are available?
4. and then: I don't care about tags, show me everything. How to do that?

(2) can be done currently via an environment variable named `LOG_TAGS`. It should change to `SEMGREP_LOG_TAGS` to avoid accidental interactions with other apps like we had recently with `LOG_LEVEL`. We should also provide and recommend a command-line option `--log-tags` and treat environment variables as a last resort.

(3): a subcommand that lists the available tags is essential to any user who doesn't have the source code handy. The list could be added to `--help`. It will be a very long list. I don't have a better suggestion at the moment.

(4) is about not making the user think. We need an easy way to show all debug info. I suggest the default action for `--debug` should be to show everything, and `--debug-tags foo,bar` would select messages that have tag `foo` or tag `bar` and would be equivalent to the combination `--debug --log-tags foo,bar`.

Edit: if `--debug` alone shows all the log messages, the relevant tags are visible and it would be an easy, natural way to identify the tag(s) to pass to `--debug-tags` or `--log-tags`. This makes point (3) less critical.

2024-04-11 09:54 UTC, IagoAbal commented
> 1. What should we tell the user when we need them to provide detailed logs?
> 2. This brings up the question: how to specify log tags?
> 3. And then: what tags are available?
> 4. and then: I don't care about tags, show me everything. How to do that?
> 
> (2) can be done currently via an environment variable named `LOG_TAGS`. It should change to `SEMGREP_LOG_TAGS` to avoid accidental interactions with other apps like we had recently with `LOG_LEVEL`. We should also provide and recommend a command-line option `--log-tags` and treat environment variables as a last resort.
> 
> (3): a subcommand that lists the available tags is essential to any user who doesn't have the source code handy. The list could be added to `--help`. It will be a very long list. I don't have a better suggestion at the moment.
> 
> (4) is about not making the user think. We need an easy way to show all debug info. I suggest the default action for `--debug` should be to show everything, and `--debug-tags foo,bar` would select messages that have tag `foo` or tag `bar` and would be equivalent to the combination `--debug --log-tags foo,bar`.
> 
> Edit: if `--debug` alone shows all the log messages, the relevant tags are visible and it would be an easy, natural way to identify the tag(s) to pass to `--debug-tags` or `--log-tags`. This makes point (3) less critical.

This PR just tries to fix a regression that was introduced by removing easy_logging and not-very-carefully replacing it with Logs. I'm not going to implement neither 2 nor 3. Point 2 is unrelated to what I want to fix here. Point 3 is out of scope, and it's also not need at present, since users are not meant to debug Semgrep by themselves.

2024-04-11 10:28 UTC, IagoAbal commented
> Maybe add "Fixes #10044" in the PR description so that issue gets linked to this PR too.
> 
> (Or maybe the fact that I just wrote a comment here triggers that already.)
> 
> EDIT: yes, this comment made the link to that issue happen, so I guess no need to do anything on your side.

The ticket was closed in some other way, but I was just reusing the ticket number for the changelog.

2024-04-11 17:24 UTC, mjambon approved these changes

2024-04-11 17:24 UTC, merged

2024-04-15 09:23 UTC, aryx reviewed
I think we should switch to use Logs.src like other OCaml libraries do instead of tags
and reserve the true Logs.debug to the core debug logs.