Fix date format of start time and end time in gl-sast report
semgrep/semgrep pull request #10691
Opened 2024-11-21 09:27 UTC by eliashaeussler

The date format of `start_time` and `end_time` in GitLab SAST reports currently does not match the expected pattern which is defined in [GitLab's report schema](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/941f497a3824d4393eb8a7efced497f738895ab4/dist/sast-report-format.json#L710). This PR aims to fix the date format according to the required pattern by replacing the RFC 3339 format with a special `YYYY-MM-DD HH:MM:SS` format.

Without this PR, GitLab SAST reports currently cannot be displayed in GitLab because of aforementioned issue:

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/5e2d8c53-70db-40df-b14b-58965ef21468">

_Note: I am not familiar with OCaml. Please bear with me if anything is wrong or conceptually bad :)_

2024-11-21 09:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/semgrep/semgrep?pullRequest=10691) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/semgrep/semgrep?pullRequest=10691) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/semgrep/semgrep?pullRequest=10691) it.</sub>

2024-11-26 12:13 UTC, aryx requested changes
Can you add a comment just before date_format explaining how it differs from RFC3339 and maybe a link to a spec somewhere.
A test would also be good.

2024-12-05 12:49 UTC, aryx commented on src/osemgrep/reporting/Gitlab_output.ml
> +  and date_format = "{year}-{mon:cX}-{day:cX}T{hour:cX}:{min:cX}:{sec:cX}" in
This actually needs to be 0X, not cX, otherwise it will bad with the 'c' character instead of '0'.
Anyway no worry I took over the PR and have a proper fix for it.
Thanks for reporting and starting the fix.

2024-12-05 12:49 UTC, aryx commented
Superseded by another PR.

2024-12-05 12:49 UTC, closed without merging

2024-12-05 14:32 UTC, eliashaeussler commented
Hi @aryx, thank you for taking care! Do you have a link to the PR you mentioned where this issue will be fixed? :)