Added python cases for pretty_print_generic
semgrep/semgrep pull request #1105
Opened 2020-06-23 16:03 UTC by emjin

Added cases necessary to python function calls, formatting them in the pythonic style.

Tested with

from metrics import send
def foo():
   bar()
   bar + send('my-report-id') + bar()
   (hi, my)
   (hi, my, bye)
   A[1]
   A[-1]
   A[1:4]
   A[1:4:-1]
   A[::-1]
   A[1:]
   if 1 == 2: foo()
   true
   3.3
   foo(self.data)

2020-06-23 18:45 UTC, aryx reviewed
looks good, not sure about those CI failures.
I had pbs myself.

2020-06-24 15:08 UTC, aryx approved these changes

2020-06-24 16:29 UTC, brendongo commented on semgrep/semgrep/synthesize_patterns.py
> +    targets = semgrep.config_resolver.resolve_targets(targets_str)
We should probably raise an exception if targets is more than one file.

See dump_ast.py

2020-06-24 16:30 UTC, brendongo commented on semgrep/semgrep/synthesize_patterns.py
> +    cmd = [SEMGREP_PATH] + args + targets_str
Should use the target that has been resolved in line 15 instead of the user arg.

2020-06-24 16:30 UTC, brendongo commented on semgrep/semgrep/cli.py
> +    output.add_argument(
Can we hide this from help text for now. See --pre-commit argument above.

2020-06-24 16:31 UTC, brendongo requested changes
Would also be nice to add an e2e test for this new command

2020-06-25 07:52 UTC, aryx commented
Bento errors seem legit:

Please fix these issues, or:

     > semgrep/semgrep/synthesize_patterns.py:2
     ╷
    2│   import tempfile
     ╵
     = 'tempfile' imported but unused

flake8 unused-module https://lintlyci.github.io/Flake8Rules/rules/F401.html
     > semgrep/semgrep/synthesize_patterns.py:4
     ╷
    4│   from typing import Optional
     ╵
     = 'typing.Optional' imported but unused

2020-06-25 07:52 UTC, aryx commented
There's lots of merge already in this diff. Let's merge that and you can fix the bento error and brendon suggestion in another PR.

2020-06-25 07:53 UTC, merged

2020-06-25 17:30 UTC, brendongo commented on .github/workflows/env-tests.yml
> +  build-core:
These should not have been in the PR

2020-06-25 17:32 UTC, brendongo commented
There were many files that should not have been in the PR. It should not have been merged like this.

2020-06-25 18:32 UTC, aryx commented
What did we do wrong? I thought emma just did git merge develop on her branch. The
Only CI error was in bento. 

Sent from my iPhone

> On 25 Jun 2020, at 19:32, Brendon Go <notifications@github.com> wrote:
> 
> ﻿
> There were many files that should not have been in the PR. It should not have been merged like this.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-25 21:37 UTC, brendongo commented
Not sure what happened but it is not immediately clear from the diff what this PR includes.