Revert "Remove sdist from pypi release"
semgrep/semgrep pull request #1294
Opened 2020-07-16 15:13 UTC by underyx

Reverts returntocorp/semgrep#1263

The original issue was "`pip install --no-build-isolation --no-binary :all: semgrep` fails with a 'semgrep-core not found' error".

After this commit, running the same command will still fail with the same error, as pip will download the last release with an sdist available. So I'd argue this commit was not an improvement.

If you run `pip install --no-build-isolation --no-binary :all: semgrep==0.15.0` with the version pinned, you get `ERROR: Could not find a version that satisfies the requirement semgrep==0.15.0` which I'd say is a worse error message than `semgrep-core not found`.

2020-07-16 18:17 UTC, brendongo approved these changes

2020-07-16 18:38 UTC, mschwager requested changes
I think we need to come up with a better solution here.

2020-07-16 18:47 UTC, mschwager approved these changes
I think #1295 is probably sufficient :+1:

Although I still wonder if we should provide a sdist at all given that you can just as easily download the corresponding repository tarball from a Github release and build things that way. Having sdists available seems like it will just set users up for failure since it's unlikely that they'll have `semgrep-core` available. This could be a documentation issue and/or a `setup.py` improvement.

Perhaps it's best to revamp `setup.py`, assume sdist installation is for internal use-cases and power-users, and go from there. We could even have a required env variable pointing to `semgrep-core` be a per-requisite for installation. Although, to that end, I think we'll need to provide more obvious ways to obtain `semgrep-core` (better docs? easily available as a GHA artifact?).

2020-07-17 14:28 UTC, merged

2020-07-17 14:29 UTC, underyx commented
> Having sdists available seems like it will just set users up for failure since it's unlikely that they'll have semgrep-core available.

That's right, but I still think they'll fail worse and have less of an idea what to do if we don't have sdists available.