adding support for running multiple YAML urls with flag 'configs'
semgrep/semgrep pull request #1693
Opened 2020-09-17 23:59 UTC by colleend

Feature request addition for issue #1237. 

Added a flag, --configs that allows you to input a list of configuration files separated by a comma (NO SPACE AFTER).

2020-09-18 18:51 UTC, aryx commented
I usually like to have in the commit message or PR a section called
Test plan:
where I describe how to test the change (to check that it actually works).
Here you linked in the PR the related issue, but I still think it's better to repeat the test plan in the commit message (later people can use git blame on the file and seeing a test plan help in my experience).

2020-09-18 18:54 UTC, colleend commented
Good point, I might write some unit tests for the flag too 🧪

2020-09-18 18:59 UTC, aryx commented
unit tests are better, but I'm ok with just a Test plan.

2020-09-18 19:32 UTC, colleend commented
Awesome, write a brief test plan in the comment, let me know if I should do anything else 👍

2020-09-18 22:47 UTC, colleend commented
wasn't passing perf tests, so trying to add --configs flag back.

2020-09-22 18:07 UTC, mschwager commented
> adding nargs to the --config results in regression in performance, so I'm adding the --configs flag back.

Could you elaborate on the regression in performance? I wouldn't expect it to behave any differently, we're essentially just adding a `for` loop. Obviously if we specify multiple configs it will take more time because we're running multiple analyses, but I don't _think_ that's what's going on here.

After briefly looking at the CI failures it looks like something was off with the argument processing, which may mean there was a bug in the multi-config implementation.

The advantage I see to `--config` instead of `--config` and `--configs` is we provide a simpler interface to users. They don't have to change or remember anything to run multiple configurations - it's just multiple values passed to the same argument. It's also simpler to maintain on our end. Instead of multiple arguments to consider it's just a `for` loop over the configs, whether it's 1 config or 5 configs. Thoughts?

2020-09-23 07:32 UTC, aryx commented
I am tempted to vote too for using multiple --config url1 --config url2 instead of the separate --configs, but at the same time I don't know any other command-line tools that allows to accumulate things by using the same flag. Actually inn OCaml the default CLI library will just pick the last one. If you do semgrep-core -lang php -lang c ... then the selected language will be 'c'.

2020-09-23 17:06 UTC, brendongo commented
FWIW it looks like it failed functionality tests and not performance tests in the config nargs commit

2020-09-24 22:45 UTC, brendongo commented
Looks like what we want is not nargs but the "append" action https://docs.python.org/3/library/argparse.html#action

But looking into this more, we would want to parse all the config files into a single datastructure of rules to run instead of looping over the config files cause if we do the later we don't get any performance benefit and end up parsing all the files NUM CONFIG number of times anyway so this is effectively invoking semgrep multiple times. Might be worth refactoring config logic cause I'm not entirely sure what config_ids are and what assumptions our codebase makes about them.

2020-09-29 18:43 UTC, brendongo requested changes
-

2020-10-02 18:00 UTC, brendongo commented
Used append action on https://github.com/returntocorp/semgrep/pull/1730

2020-10-02 18:00 UTC, closed without merging