Spacegrep integration in Python layer
semgrep/semgrep pull request #1848
Opened 2020-10-16 15:42 UTC by minusworld

This PR integrates spacegrep into the Python layer. It can be invoked using the language "generic".

```
$ semgrep -l generic -e '## $X' README.md
README.md
63:## Getting
98:## Examples
112:## Try
146:## Resources
160:## Usage
162:## Command
166:## Exit
174:## Upgrading
189:## Contributing
204:## Commercial
ran 1 rules on 1 files: 10 findings
```

A few things of note:
- The spacegrep offsets are bit off; the function `_patch_lines` fixes that for now.
- Semgrep needs the `extra['lines']` key which is a list of matched lines. `_patch_lines` handles this for now.
- This integration assumes spacegrep was installed somewhere that is on the system PATH.
- An observation: Semgrep metavariables include the dollar sign '$' in front of them in the JSON output; spacegrep excludes the dollar sign at the moment.

2020-10-16 16:57 UTC, mjambon commented on semgrep/semgrep/spacegrep.py
> +        lines[-1] = lines[-1][: end_c - 1]
ok, I'll look into this. I specifically added 1 here and there before exporting to json because a comment I found in the ocaml code said so.

2020-10-16 16:57 UTC, mjambon approved these changes

2020-10-16 17:59 UTC, brendongo requested changes
Is spacegrep executable correctly packaged in wheel and docker images?

2020-10-17 06:06 UTC, mjambon commented
@brendongo 
> Is spacegrep executable correctly packaged in wheel?

I don't know if there's any subtlety that I may have missed. I'm not familiar with python wheels.

@minusworld added tests and they pass, after I made some fixes. The status of `spacegrep` and `spacecat` is the same as `semgrep-core`. All 3 are executables built from ocaml/C/C++ source. They're statically linked for linux and "mostly statically linked" for osx.

2020-10-19 17:21 UTC, brendongo commented
Maybe worth taking a look at https://github.com/returntocorp/semgrep/blob/develop/semgrep/setup.py#L88 for how the python scripts install semgrep-core in the correct place.

2020-10-19 20:06 UTC, mjambon commented
@brendongo I would have missed it if you hadn't looked into it. Is there a way to test this? automatically?

2020-10-19 22:00 UTC, brendongo commented
The python unit and e2e tests should be failing since they don't have spacegrep installed in their environments... not sure why they pass tbh :D

2020-10-19 22:07 UTC, brendongo commented
To test locally: `python setup.py sdist bdist_wheel` in repo_root/semgrep will generate the wheel file. To test if that wheel file contains all the necessary files I would make sure `which spacegrep` doesnt find anything, install the wheel using `pip3 install PATH_TO_DOT_WHL_FILE` and then checking that `which spacegrep` now points to where it should

2020-10-20 16:40 UTC, brendongo commented
IMO we could get this in as is, not advertise the functionality and work on getting it building on pip in a follow up PR. For now BYO spacegrep might be fine.

2020-10-20 19:04 UTC, mjambon commented
@brendongo I'll try to get this fixed today-ish. I'll learn something.

2020-10-21 03:08 UTC, mjambon commented
Here's what I did:

* re-enabled the installation of executables into `/usr/bin` for the tests to work. An alternative would be to first create the wheel package and then install it and use it for the tests. This is done somewhere else and it looks like too much too change for now.
* added `spacegrep` and `spacecat` to the wheel package just like `semgrep-core`. This is not tested, see point above.

That's not much but it works in theory. In practice, we're getting a missing blank in a test result, which seems to come out of nowhere (maybe a library that wasn't pinned and changed its behavior). You can see it [here](https://github.com/returntocorp/semgrep/pull/1848/checks?check_run_id=1284435787#step:8:112). We expect the string `This \noperation` and instead we get `This\noperation`. This is from the file `semgrep/tests/e2e/snapshots/test_check/test_registry_rule/results.json`. Let me know if I should just remove the space in that file and move on.

2020-10-21 03:20 UTC, brendongo approved these changes

2020-10-21 05:19 UTC, merged