type outline for kotlin
semgrep/semgrep pull request #2288
Opened 2020-12-18 00:42 UTC by colleend

2020-12-18 08:41 UTC, aryx commented
The test plan is not great because we actually don't see any type in the AST. fparams is currently empty.

2020-12-18 08:43 UTC, aryx commented
Also I don't understand why the body of the function in the AST is this complicated Call (x, return this)
when in the code you have just return x;
Are you sure you put the dump of the right file?

2020-12-18 08:51 UTC, aryx requested changes

2020-12-18 08:51 UTC, aryx commented on semgrep-core/parsing/Parse_kotlin_tree_sitter.ml
> +       ParamPattern (PatType v1)
I tyink you can build a ParamClassic with p_type = v1, and p_name = None,
like we do in C for function signatures.

2020-12-18 08:51 UTC, aryx commented on semgrep-core/parsing/Parse_kotlin_tree_sitter.ml
> +   | _ ->
in grammar.js they use repeat1($._quest)
and _quest: $ => "?"
which means there is at least one "?", so you can write the pattern:
| [] -> raise Impossible (* see repeat1($._quest) in grammar.js *)

2020-12-18 08:51 UTC, aryx commented on semgrep-core/parsing/Parse_kotlin_tree_sitter.ml
> +       ParamPattern (PatType v1)
There is even AST_generic.param_of_type() to help build this parameter_classic type.

2020-12-18 08:51 UTC, aryx commented on semgrep-core/parsing/Parse_kotlin_tree_sitter.ml
> +  let param = {
You can factorize a bit and do let param = { (AST_generic.param_of_id v1) with ptype = v3 }

2020-12-18 18:00 UTC, colleend commented
🤦‍♀️ !! thanks for noticing!! fparams is empty because I initially set the fparams to empty list 🤦 🤦 

I'll make the changes to the current code and think of a better test plan. Ty for the comments 🎉

2020-12-28 13:47 UTC, aryx approved these changes

2020-12-28 13:47 UTC, merged