Add Lua language support
semgrep/semgrep pull request #2312
Opened 2020-12-27 01:24 UTC by Ruin0x11

Adds Lua parsing support. It gets a 99.999% success rate on a fairly large corpus.

There isn't support yet for using semgrep patterns yet; this only allows parsing the AST with semgrep-core. #2280 needs to be finished first.

There are a lot of changes to other submodules needed:

https://github.com/returntocorp/pfff/pull/362
https://github.com/returntocorp/semgrep-grammars/pull/9
https://github.com/returntocorp/ocaml-tree-sitter/pull/131
https://github.com/returntocorp/ocaml-tree-sitter-lang/pull/3

Also, the version of `tree-sitter-lua` used was customized to fix some issues. 

https://github.com/Azganoth/tree-sitter-lua/compare/master...Ruin0x11:fix-call-expression

2020-12-27 02:20 UTC, Ruin0x11 commented
I'm trying to debug, but I'm not able to get a backtrace for some reason. I don't know much OCaml. Shouldn't `-g` be specified by default with `dune`?

```
$ OCAMLRUNPARAM=b ./_build/default/cli/Main.exe -lang lua ../ocaml-tree-sitter/lang/lua/stat.tmp/lua/lua/testes/calls.lua -dump_ast -report_fatal_errors
../ocaml-tree-sitter/lang/lua/stat.tmp/lua/lua/testes/calls.lua:1:0: Fatal Error: (Failure nth)
Called from unknown location
Called from unknown location
Called from unknown location

Fatal error: exception (Failure nth)
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
```

2020-12-28 13:52 UTC, aryx commented
@Ruin0x11 did you sign the CLA so I can merge your changes.

2020-12-28 13:53 UTC, aryx commented
Weird that you don't have any backtrace. Which OCaml version are you using, which OS, which opam?
Once it's merged I can try to debug it myself.

2020-12-28 14:35 UTC, ievans commented
@aryx CLA is signed! I’ll update the bot shortly. 

@Ruin0x11 this is a terrific contribution. I am in awe!

2020-12-28 15:30 UTC, ievans commented
@cla-bot check pls

2020-12-28 15:31 UTC, ievans commented
retrying, @cla-bot check pls

2020-12-28 15:32 UTC, ievans commented
retrying

@cla-bot check pls

2020-12-28 15:39 UTC, aryx commented
I think the  bot is in vacation too.

2020-12-28 15:46 UTC, ievans commented
fixed trailing comma in the json file...

@cla-bot check pls

2020-12-28 20:12 UTC, aryx approved these changes
I guess the translation to the generic AST could be improved at a few places, but
it's a good start. Let's merge this and improve later.

2020-12-28 20:12 UTC, aryx commented on Makefile
> +	# cd ocaml-tree-sitter && ./scripts/install-tree-sitter-lib
why this?

2020-12-28 20:12 UTC, aryx commented on semgrep-core/parsing/Parse_lua_tree_sitter.ml
> +  { G.name = name; attrs = [G.KeywordAttr (G.LocalDef, local)]; tparams = [] }
Maybe we can reuse Static to represent local def. static int f() { ...} declare a local function in C (local to the file; not exported).

2020-12-28 20:12 UTC, aryx commented on semgrep-core/parsing/Parse_lua_tree_sitter.ml
> +  String.concat "." (v1::v2)
probably need to use Dot or the name type with its qualifier instead of just using a string.

2020-12-28 20:12 UTC, aryx commented on semgrep-core/parsing/Parse_lua_tree_sitter.ml
> +       G.Call (G.IdSpecial (G.Op G.FloorDiv, v2), fb [G.Arg v1; G.Arg v3])
Could be just Div, not FloorDiv.

2020-12-28 20:12 UTC, aryx commented on semgrep-core/parsing/Parse_lua_tree_sitter.ml
> +       G.Call (G.IdSpecial (G.Op G.Div, v2), fb [G.Arg v1; G.Arg v3])
ah ok, you probably know better; I am not familiar with Lua.

2020-12-28 20:12 UTC, aryx commented on semgrep-core/parsing/Parse_lua_tree_sitter.ml
> +   | `Num tok -> G.L (G.Float (fst (str env tok), token env tok)) (* number *)
you can do
let (s, tok) = str env tok in
G.L (G.Float (s, tok))

2020-12-28 20:12 UTC, aryx commented on semgrep-core/parsing/Parse_lua_tree_sitter.ml
> +let parse file =
impressive work! Thx a lot! Lots of boilerplate to fill.

2020-12-28 20:14 UTC, aryx requested changes
I think you just need to restore the line in the Makefile to install-tree-sitter and we're good to go.
Right now the CI failure is because of this missing line I think.

2020-12-31 09:35 UTC, Ruin0x11 commented
I fixed the qualified name thing as well as the Makefile. The AST only gets about a 75% success rate on the corpus I provided because of some out of bounds errors, but I'm not sure how to debug without backtraces. I hope to figure it out eventually.

2020-12-31 09:37 UTC, Ruin0x11 commented
Also, here is my system info. I use Arch Linux.

```
 » opam --version                                                                                                                                                                                                                                                                         ~/build/work/semgrep % 1
2.0.7
 » dune --version                                                                                                                                                                                                                                                                           ~/build/work/semgrep % 0
2.7.1
 » ocaml --version                                                                                                                                                                                                                                                                          ~/build/work/semgrep % 0
The OCaml toplevel, version 4.11.1
 » uname -a                                                                                                                                                                                                                                                                                 ~/build/work/semgrep % 0
Linux nori 5.4.85-1-lts #1 SMP Mon, 21 Dec 2020 19:28:35 +0000 x86_64 GNU/Linux
```

2020-12-31 13:59 UTC, aryx approved these changes

2020-12-31 13:59 UTC, merged

2021-01-04 16:58 UTC, aryx commented
Maybe you can try opam switch create 4.09.1 which is the compiler version we are using.
I just use dune build and I get the debugging information.
Here is what I get on lua/testes/calls.lua:
```
pad@yrax:~$ OCAMLRUNPARAM=b ./semgrep/_build/default/cli/Main.exe -dump_ast ~/work/lang-lua/lua/testes/calls.lua 
/home/pad/work/lang-lua/lua/testes/calls.lua:1:0: Fatal Error: (Failure nth)
Raised at file "parsing/Parse_code.ml", line 167, characters 24-27
Called from file "parsing/Parse_code.ml", line 278, characters 30-60
Called from file "cli/Main.ml", line 997, characters 10-76
Called from file "pfff/h_program-lang/Error_code.ml", line 391, characters 4-8

Fatal error: exception (Failure nth)
Raised at file "parsing/Parse_code.ml", line 167, characters 24-27
Called from file "parsing/Parse_code.ml", line 278, characters 30-60
Called from file "cli/Main.ml", line 997, characters 10-76
Called from file "pfff/h_program-lang/Error_code.ml", line 391, characters 4-8
Re-raised at file "pfff/h_program-lang/Error_code.ml", line 398, characters 10-13
Called from file "pfff/commons/Common.ml", line 95, characters 14-18
Re-raised at file "pfff/commons/Common.ml", line 100, characters 10-11
Called from file "pfff/commons/Common.ml", line 1342, characters 12-16
Re-raised at file "pfff/commons/Common.ml", line 1340, characters 8-301
Called from file "pfff/commons/Common.ml", line 1310, characters 45-49
Called from file "pfff/commons/Common.ml", line 95, characters 14-18
Re-raised at file "pfff/commons/Common.ml", line 100, characters 10-11
Called from file "pfff/commons/Common.ml", line 1307, characters 6-10
Called from file "cli/Main.ml", line 1370, characters 2-146
pad@yrax:~$ ocaml --version
The OCaml toplevel, version 4.09.1

```