Add v0 opt-in aggregate metrics
semgrep/semgrep pull request #3071
Opened 2021-05-11 00:23 UTC by brendongo

PR checklist:
- [ ] changelog is up to date

2021-05-11 02:17 UTC, adamberman approved these changes
Approved, but two overall comments (totally fine to add later IMO): 1) we should add tests for this, and 2) have you manually tested with semgrep-agent to make sure things are still working there?

2021-05-11 02:17 UTC, adamberman commented on semgrep/semgrep/metric_manager.py
> +    """
Might be nice to put a comment describing how this class is meant to be used/why it is a singleton for ease of use. But also totally fine if you just want to follow up with a commit later for expediency :)

2021-05-11 02:17 UTC, adamberman commented on semgrep/semgrep/metric_manager.py
> +                logger.info("Failed to send anonymized metrics.")
should we log the exception?

2021-05-11 02:23 UTC, brendongo commented
Waiting on privacy doc

2021-05-11 15:28 UTC, DrewDennison requested changes
Let's review spec

2021-05-12 03:37 UTC, DrewDennison approved these changes
LGTM

2021-05-12 05:55 UTC, adamberman commented
LGTM too

2021-05-13 16:13 UTC, merged