synthesizing: Pattern_from_Targets ExprStmt lists
semgrep/semgrep pull request #3488
Opened 2021-07-08 17:50 UTC by defreez

Add support for targets that are ExprStmt lists in Pattern_from_Targets.

For example, two separate targets might be

```
x = req.query.foo;
exec(x);
```

and

```
y = req.query.foo;
exec(y);
```

yielding the pattern

```
$X = req.query.foo;
exec($X);
```

Limitations:
- Targets must be of equal length. Cannot yet generate ellipsis for
statements to equalize length of targets.
- No additional support for statements other than ExprStmt.

PR checklist:
- [ ] changelog is up to date

2021-07-08 17:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/returntocorp/semgrep?pullRequest=3488) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/returntocorp/semgrep?pullRequest=3488) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/returntocorp/semgrep?pullRequest=3488) it.</sub>

2021-07-09 17:49 UTC, emjin commented
See https://github.com/returntocorp/semgrep/tree/develop/doc#development-workflow for how to make the lint errors go away.

2021-07-10 00:58 UTC, defreez commented
Thanks @emjin I have the pre-commit installed now.

2021-07-11 00:08 UTC, emjin commented on semgrep-core/src/synthesizing/Pattern_from_Targets.mli
>  (* limited to expressions for now *)
No longer true :D

2021-07-11 00:08 UTC, emjin commented on semgrep-core/src/synthesizing/Range_to_AST.ml
> +let range_of_ast = V.ii_of_any $ Range.range_of_tokens
@aryx I don't think we tend to use this operator in our codebase?

2021-07-11 00:08 UTC, emjin commented on semgrep-core/src/synthesizing/Synthesizer.ml
> +  let a_opt = Range_to_AST.many_at_range r ast in
Is this a preemptive change? It looks like you later just take one element

2021-07-11 00:13 UTC, emjin requested changes
Looks pretty good! I think, instead of just always expecting an `AST_generic.any list list` in generate patterns, it would be better to take programs (and blocks, though you can start by separating them) and compare them in the element-by-element fashion. This will also set you up better for when you have to handle anything nested.

2021-07-11 00:13 UTC, emjin commented on semgrep-core/src/synthesizing/Pattern_from_Targets.ml
> +    pattern_instrs list list =
Similarly to comment in mli, I don't think this needs to be a `list list`

2021-07-11 00:13 UTC, emjin commented on semgrep-core/src/synthesizing/Pattern_from_Targets.mli
> +  Config_semgrep.t -> AST_generic.any list list -> Lang.t -> Pattern.t list
I don't think we should ever need this to be a list list. A Pr program is an any, and other statement lists are generally contained within blocks.

2021-07-12 13:58 UTC, defreez commented
Thanks for the review :) Agreed that the `list list` interface is clumsy. I'll update it, hopefully by tomorrow.

2021-07-13 09:35 UTC, aryx approved these changes
This looks great.
I think we can merge this.

2021-07-13 09:37 UTC, aryx commented on semgrep-core/src/synthesizing/Range_to_AST.ml
> +let range_of_ast = V.ii_of_any $ Range.range_of_tokens
What do you mean? The $?

2021-07-13 09:41 UTC, aryx commented on semgrep-core/src/synthesizing/Range_to_AST.ml
> +let range_of_ast = V.ii_of_any $ Range.range_of_tokens
I tend to prefer to put the parameters instead of using https://wiki.haskell.org/Pointfree style.

2021-07-13 09:45 UTC, aryx commented
The next steps are to remove those list list like @emjin suggested and start writing some
test infrastructure where we can add some code examples and assert the resulting pattern has a certain form.
Something like in Unit_synthesizer.ml

where you can add a test like

let p1 = "
x = req.query.foo;
exec(x);
"
in
let p2 = "
y = req.query.foo;
exec(y);
"
in
let res = do_the_magic Lang.Java [p1; p2] in
let expected = "
$X = req.query.foo;
exec($X);
"
in
assert_same_ast "it should match" res expected

2021-07-13 09:46 UTC, aryx approved these changes

2021-07-13 09:46 UTC, merged