Do something about stack overflows
semgrep/semgrep pull request #3625
Opened 2021-07-29 09:17 UTC by mjambon

* Print a warning when the stack size exceeds 7 MB.
* Raise a `Stack_overflow` exception when the stack size exceeds half of the user-specified memory limit (requires 'ulimit -s unlimited' or equivalent).

See discussions and plan: https://github.com/returntocorp/semgrep/issues/3623

PR checklist:
- [ ] documentation is up to date
- [ ] changelog is up to date

2021-07-29 10:26 UTC, IagoAbal commented on semgrep-core/src/cli/Main.ml
>      let alarm = Gc.create_alarm limit_memory in
> create_alarm f will arrange for f to be called at the end of each major GC cycle, starting with the current cycle or the next one. A value of type alarm is returned that you can use to call delete_alarm.

I guess there is no warranty that the alarm will be called before the stack overflows?

2021-07-29 11:30 UTC, IagoAbal commented on semgrep-core/src/cli/Main.ml
>      let alarm = Gc.create_alarm limit_memory in
But it may work for the cases that we have experienced, I believe that previous to the stack overflow you could see increased allocation. Have you tested this?

2021-07-30 08:35 UTC, aryx commented
You need to add Memory_limiit.ml

2021-07-30 08:35 UTC, aryx requested changes
missing file

2021-07-31 04:18 UTC, mjambon commented
From what I can tell, simply using the GC alarm causes a 6x slowdown. We may have not seen it before because we'd not set a GC alarm with the default settings, but now we do.

2021-07-31 09:16 UTC, aryx commented
Ok, for once the semgrep benchmark regression test played its role! Glad it can at least catch those big regressions :)

2021-07-31 11:21 UTC, mjambon commented
I think it should work with performance degradation now.

Stack overflow prevention doesn't work very well because it requires a lot of allocation per function call for the GC alarm to run frequently enough (see the unit test).

2021-08-02 09:58 UTC, IagoAbal commented on CHANGELOG.md
> +- eliminate 6x slowdown when using the '--max-memory' option
Nice!

2021-08-02 10:07 UTC, IagoAbal commented
Fixing the slowdown for `-max_memory` was a very nice side-effect of this PR.

The stack overflow detection I am not sure if it's worth while. It seems to be an issue to be solved in the OCaml compiler, and apparently it only affects ARM. It only works under very specific conditions (this is not discussed in the code or in `-max_stack`...), it must trigger a major collection at the right time. Do we know if it actually works for the stack overflows that we experienced?

I think the right move would be to fix Semgrep so it doesn't get killed if anything happens when analyzing some specific file.

2021-08-02 15:55 UTC, mjambon commented
Yeah, `-max_stack` doesn't work well - I had to put a lot of artificial allocation in the `grow_stack` function used in the unit tests otherwise it wouldn't work. I think it's misleading: we could still have segfaults (on those archs) due to stack overflow but not realize it because we expect `-max_stack` to work.

I'm going to do the following:
- remove `-max_stack` completely
- keep the other things this branch fixes (fix the perf issue with `Gc.compact()`, monitor heap+stack memory rather than just heap with `-max_memory`)
- always create a GC alarm so that all our tests and all production code run with it.

2021-08-02 23:58 UTC, merged