optimizing: Analyze_rule: Fix CNF simplification in step1
semgrep/semgrep pull request #3948
Opened 2021-09-28 08:23 UTC by IagoAbal

When a term in an OR cannot be checked with a regex, we have to assume
that the term holds and thus reduce the entire OR to "true".

Closes #3755

test plan:
make test # test included

TL;DR

For example:

    - pattern-either:
        - patterns:
            - pattern: $X.sha1("$RE")
            - metavariable-regex:
                metavariable: $RE
                regex: (?i)md2
        - patterns:
            - pattern: $X.getMd2Digest(...)

This is seen by Analyze_rule as:

    OR
        AND (contains "sha1") (cannot-check)
        AND (contains "getMd2Digest")

When converting it into CNF we get:

    AND
        OR (contains "sha1") (contains "getMd2Digest")
        OR (cannot-check) (contains "getMd2Digest")

The bug was caused by incorrectly simplifying this in step1 as:

    AND
        OR (contains "sha1") (contains "getMd2Digest")
        OR (contains "getMd2Digest")

When it should be:

    AND
        OR (contains "sha1") (contains "getMd2Digest")

PR checklist:
- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [ ] Change has security implications (if so, ping security team)

2021-09-28 09:17 UTC, aryx commented
what is this 'cannot-check'?

2021-09-28 09:19 UTC, aryx commented
Also the test plan say 'test included' but I don't see any tests in the PR.

2021-09-28 09:20 UTC, aryx requested changes
Can you add some tests with the example you put in the PR?

2021-09-28 10:29 UTC, IagoAbal commented
> Also the test plan say 'test included' but I don't see any tests in the PR.

Ooops, I forgot to `git add`!

2021-09-28 12:12 UTC, IagoAbal commented
> 🚫 Benchmark semgrep.bench.zulip.std is too slow: +52.7% (+4.142 s)
> 
> 🚫 Benchmark semgrep.bench.apache.std is too slow: +150.2% (+20.659 s)
> 
> 🚫 Benchmark semgrep.bench.lodash.std is too slow: +58.9% (+2.980 s)

Will try to check these slow downs, just in case there might be something we can do about them. But if the speed up was caused by incorrectly filtering files we have no other choice... 😞

2021-09-28 13:49 UTC, IagoAbal commented
Damn I had a very silly bug.

2021-09-28 14:00 UTC, IagoAbal commented
Perhaps we need a small test suite just for -filter_irrelevant_rules.

2021-09-28 15:57 UTC, IagoAbal commented
@aryx if everything is green (as I hope) then I believe this is now ready. I fixed a bug that was causing the perf regressions, and I added a couple of tests. For irrelevant rules I had to add a separate test suite (tests/OTHER/irrelevant_rules), where the test fails if either a) Analyze_rule cannot produce a regex prefilter, or b) the regex filter determines that the file is _relevant_ (it is expected to be _irrelevant_). For relevant rules that produce matches we can use tests/OTHER/rules. If we need to test relevant rules that produce no matches then we need to add a new test suite or rethink things a bit.

2021-09-28 16:39 UTC, emjin commented
Woah the benchmark tests were useful!!

2021-09-28 20:18 UTC, IagoAbal commented
> Woah the benchmark tests were useful!!

They're definitely useful! My main complain is that the warnings fire too often. In the two cases where they flagged a real problem the slow down was 50% or more. Here the apache benchmark was twice as slow, with a +13s delta. But I don't think our setup allows us to reliably detect very subtle regressions that barely affect performance, it's very difficult to distinguish those from noise.

2021-09-29 08:54 UTC, aryx commented
great indeed that the benchmark helped finding bugs!

2021-09-29 09:29 UTC, aryx approved these changes
This is great! Nice find.

2021-09-29 09:29 UTC, merged