Fix problem with If body that needs to be a Block + tests
semgrep/semgrep pull request #4024
Opened 2021-10-08 09:18 UTC by mjambon

I found out the hard way that a pattern of type `stmts` can't match an `If` body if it's not a `Block`, because only a `Block contains `stmts` (a list of statements).

PR checklist:
- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

2021-10-08 12:59 UTC, aryx requested changes

2021-10-08 12:59 UTC, aryx commented on semgrep-core/src/parsing/ast/Bash_to_generic.ml
> +   of statements.
I don't understand. If the pattern is a list of statements (so at least 2 elts), why would we want that it
maches a single stmt? 
Also your examples do not contain any pattern with multiple statemnet; it's each time just an expression pattern.

2021-10-08 22:17 UTC, mjambon commented on semgrep-core/src/parsing/ast/Bash_to_generic.ml
> +   of statements.
The pattern `a` (in bash) is currently parsed as a list of statements rather than a single statement, just like `a; b`. The pattern `a` then doesn't match `if b; then a; fi` unless the `a` after `then` is also a list of statements, which wasn't the case. It looks like a question of consistency. Perhaps it gets easier if we have that in mind, I'm not sure. The other thing I'm not sure about is how to enforce consistency and how to catch these mistakes.

What I can do is:
* This PR: have all single statements be actually a Block. This doesn't make much sense in retrospect. Instead, it would make more sense to change the type of the `then` branch to `stmts` instead of `stmt`, but that may be a bad idea for other reasons.
* Ensure that all patterns of the form `Block (open_br, [stmt], close_br)` are simplified to `stmt`.

The second solution seems better to me right now. However, the simplification should only take place if the brackets are fake, as in the case of bash statements, which is dirty compared to directly constructing the tree correctly in the first place. At least we can document the `Block` construct where it is defined in `AST_generic` and explain what can go in there.

I'll make a PR implementing the second solution.

2021-10-09 01:23 UTC, mjambon commented on semgrep-core/src/parsing/ast/Bash_to_generic.ml
> +   of statements.
See https://github.com/returntocorp/semgrep/pull/4031 for the alternate solution.

2021-10-09 03:15 UTC, closed without merging