Enforce metavariable equality between sources/sinks/sanitizers, and show metavariables in taint mode messages
semgrep/semgrep pull request #4073
Opened 2021-10-14 22:54 UTC by mmcqd

We can now write rules that use the same metavariable across sources/sinks/sanitizers, and refer to these metavariables in match messages. Currently if a sink could be matched with multiple possible metavariable assignments it will be matched twice by `semgrep-core`, but `semgrep` will filter out all but one of these matches.

PR checklist:
- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

2021-10-21 07:35 UTC, aryx requested changes
I don't want the core to depends on analyzing. There has to be a way to avoid this dependency.
In fact in core/dune we should remove pfff-lang_GENERIC-analyze, it's not currently needed; not sure why it was there in the first place.

2021-10-21 07:41 UTC, aryx commented
Maybe you can move Dataflow_tainting.ml in engine/, and add a note that it used to be in analyzing/, but with
metavariable checking the environment now depends on Pattern_match.t, which means it depends on semgrep-core/core.
Then say it can't be in analyzing/ because
we want analyzing/ to be independent of semgrep-core/core because it's used in other projects (e.g., codemap from aryx)

2021-10-22 12:46 UTC, aryx requested changes
Asking for more comments mostly.

2021-10-22 12:46 UTC, aryx commented on semgrep-core/src/core/Pattern_match.ml
> +type int_range = int * int * int * int [@@deriving ord]
A comment on what those 4 ints are?
lines? columns? if it's for the left and right part, maybe they need to better grouped.

2021-10-22 12:46 UTC, aryx commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +type mapping = PM.Set.t Dataflow.mapping
So PM.Set.t is a set of pattern matches. How does it related to "a variable is 'tainted'"?
I would expect a bool Dataflow.mapping for "whether a variable is tainted".

2021-10-22 12:46 UTC, aryx commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +let unify_meta_envs env1 env2 =
comment, what this function is doing? Why we need it?

2021-10-22 12:46 UTC, aryx commented on semgrep-core/src/engine/Dataflow_tainting.mli
> +  is_source : AST_generic.any -> Pattern_match.t list;
Can you add a comment on the meaning of the return type?
Before with bool it was pretty clear "whether or not this expr/stmt/any is a source.
But now why does it return a set of matches? If it's to allow to compare metavariables in different places,
then why we need Pattern_match.t? why not just a metavariable environment?

2021-10-22 18:00 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +let ( <|> ) = PM.Set.union
IMO it's better to avoid defining custom operators unless they are going to be used a lot. If I encounter `PM.Set.union` I immediately know what that means, whereas if I read `<|>` I need to go look up what `<|>` means.

2021-10-22 21:57 UTC, mmcqd commented on semgrep-core/src/engine/Dataflow_tainting.mli
> +  is_source : AST_generic.any -> Pattern_match.t list;
Hmm you're right that we only need the metavariable environment for this, but tracking the pattern matches that originated a variable's taint will make it easier to implement something that displays information about how a sink ended up being tainted. I don't know whether or not it's worth preemptively tracking this information if this PR isn't going to be implementing that feature. It wouldn't be hard to switch to only tracking metavar envs if you think that would be a better idea.

2021-10-22 23:04 UTC, mmcqd commented on semgrep-core/src/core/Pattern_match.ml
> +type int_range = int * int * int * int [@@deriving ord]
I'm just using builtin compare on the range_locs now. Seemed more straightforward than picking some ints to extract like I was doing here.

2021-10-25 09:14 UTC, IagoAbal commented on semgrep-core/src/core/Pattern_match.ml
> +     but is potentially a source of unexpected behavior.
What kind of unexpected behavior? I guess the worst that can happen is that we get duplicate findings?

2021-10-25 09:31 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +        match List.assoc_opt mvar env2 with
You can use let-punning https://ocaml.org/manual/bindingops.html if you want to simplify some `option`-handling code, e.g.:
```ocaml
let (let*) = Option.bind in
...
let* xs = xs in
...
| None -> Some ((mvar, mval) :: xs)
```

2021-10-25 12:34 UTC, IagoAbal commented
> I don't want the core to depends on analyzing. There has to be a way to avoid this dependency.

Sorry that I missed the initial context. @mmcqd was the `core` that depended on `analyzing`? Or `analyzing` that depended on `core`? I would only expect `Dataflow_tainting` to depend on `Pattern_match.t`.

2021-10-25 12:39 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +let update_meta_envs pm =
For readability I think it's better to declare the other argument that this function expects. Or write down the return type.

2021-10-25 12:50 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +let update_meta_envs pm =
It could be beneficial to use ocamldoc tags (https://ocaml.org/manual/ocamldoc.html#ss:ocamldoc-tags): 
```ocaml
(* @param sink_pm Pattern match of a sink.
   @param src_pms Set of pattern matches corresponding to sources.
   @returns [sink_pm] unified with each [src_pms] when possible. *)
let update_meta_envs sink_pm src_pms = 
  ...
```

2021-10-25 13:02 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +  | Some data' -> Hashtbl.add env x (f data')
You should probably use `Hashtbl.replace` here.

2021-10-25 13:09 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +      if PM.Set.is_empty found then tainted_pms
```ocaml
if not (PM.Set.is_empty found) then config.found_tainted_sink found env;
tainted_pms
```

2021-10-25 13:13 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +            varmap_update in' (str_of_name var) tainted (PM.Set.union tainted)
I think it could be more readable to just use `VarMap.update` here.

2021-10-25 13:15 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +        | _, Some var ->
Better write this `| false, Some var ->`, since AFAICT the `_` must be `false`, and the RHS only makes sense when it's `false`.

2021-10-25 13:16 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +        | _ -> in')
This could be a little bit more clear if it were `| _, None -> ...`. It has the nice effect that you can now reorder the clauses without altering the semantics.

2021-10-25 13:18 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +            hashtbl_update fun_env (str_of_name var) tainted
I would probably inline `hashtbl_update` here, it's the only place where it's used anyways.

2021-10-25 13:19 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +        | _ -> in')
`| None -> in'`

2021-10-25 13:23 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.mli
> +  is_source : AST_generic.any -> Pattern_match.t list;
We can just add a short comment. We have future plans for the `Pattern_match.t` (debugging mode and maybe special pretty-printing of taint matches).

2021-10-25 14:57 UTC, IagoAbal commented on semgrep-core/tests/tainting_rules/js/metavar_eq_conditional.js
> +var source = cond ? get(A) : get(f(A))
Maybe `get(f(A))` should be `get(f(B))` to make the test more relevant?

2021-10-25 15:05 UTC, IagoAbal commented on semgrep-core/tests/tainting_rules/js/metavar_eq_conditional.js
> +var source = cond ? get(A) : get(f(A))
Or maybe I'm not getting right what you're trying to test here?

2021-10-25 15:09 UTC, IagoAbal commented on semgrep-core/src/core/Pattern_match.ml
> +  type t = pm
Try `type nonrec t = t`.

2021-10-25 15:11 UTC, mmcqd commented on semgrep-core/tests/tainting_rules/js/metavar_eq_conditional.js
> +var source = cond ? get(A) : get(f(A))
The idea of this test is that since the sink can either be on $X or f($X), there's two metavariable assignments that would make the sink tainted. Either $X = A or $X = f(A). I wanted to check that semgrep-core would correctly report the tainted sink twice, and it does. Though `make test` can't actually check that the double report happens I think.

2021-10-25 23:46 UTC, mmcqd commented on semgrep-core/src/core/Pattern_match.ml
> +     but is potentially a source of unexpected behavior.
Yep. Updated comment to mention this.

2021-10-27 08:18 UTC, aryx approved these changes

2021-10-27 08:18 UTC, aryx commented on semgrep-core/src/core/Pattern_match.ml
> +module Set = Set.Make (struct
Maybe a comment like
"This special Set is used in the dataflow tainting code, which manipulate sets of matches (actually we currently care only about the metavariables in the matches) associated to each variables.".

2021-10-27 08:18 UTC, aryx commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +(* @param env1 Metavariable environment.
meh on those @param and @return. I'd rather see a type that says the same thing.
I would keep the @ returns  comment (but would remove the leading @).

2021-10-27 08:18 UTC, aryx commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +(* @param sink_pm Pattern match of a sink.
ok here the comments are not bad. They don't just paraphrase a type.

2021-10-27 08:18 UTC, aryx commented on semgrep-core/tests/tainting_rules/js/metavar_eq_conditional.js
> +var source = cond ? get(A) : get(f(A))
ok this comment about "the idea of this test ..." should be put in the code. It's a useful comment.

2021-10-27 08:18 UTC, aryx commented on semgrep-core/tests/tainting_rules/js/metavar_eq_conditional.js
> +var source = cond ? get(A) : get(f(A))
Also I think this test is too subtle, and like you say 'make test' just check if something is reported at a line, so it does
not really enforce what you think, so maybe there is a better way to write the test that would enforce what you say.

2021-10-27 08:18 UTC, aryx commented on semgrep-core/tests/tainting_rules/js/metavar_eq_simple.js
> +
Again, the test is a bit confusing because the pattern-source is get($X),
but then in the pattern-sink you actually don't care about the source (even though it's passed as an  extra parameter),
you just check for $X, which now make the reader think that $X itself is a source.

Maybe I would not pass the source1, source2, ... extra arguments to sink, they are distracting.

I wonder again if there are better tests. This looks like taint use-cases noone would need.
Why did we implement this check-metavar-equality in the first place? Do we have a simple example showing
the needs for the feature?

2021-10-27 08:20 UTC, IagoAbal approved these changes

2021-10-27 08:30 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +(* @param env1 Metavariable environment.
Just to say that `env1` is a `"Metavariable environment."` I agree it's not necessary. But if you are going to say something long about a parameter, then it's better to use `@param` as this is a standard tag and helps reading more efficiently. Which is why I suggested `@param` in the first place.

A common style to doc this is also:
```ocaml
(* [unify_meta_envs env1 env1] returns [Some (union env1 env2)] if [env1] and [env2] contain no conflicting metavariable assignments, otherwise [None]. *)
```

2021-10-27 09:01 UTC, IagoAbal commented on semgrep-core/tests/tainting_rules/js/metavar_eq_simple.js
> +
IIRC this is a feature that @nbrahms pointed out that we were lacking and it made sense to me too. The behavior overall seems consistent with what we do in search mode, although I guess there may be different ways of seeing it.

It also made sense because we want to support referring to any of these metavariables in the message. Once you allow that, it also makes sense to allow referring to a metavariable bound while matching the source, and once you are there then it makes sense to do this kind of "unification" anyways. Also, most of the work was already needed simply to identify the source of taint, which is something that users have asked for.

I agree the tests are somewhat artificial. In this particular case we don't have good motivating examples for the "filtering" aspect of it. Maybe @minusworld has encountered some real rules where this is useful?

2021-10-27 09:07 UTC, aryx commented on semgrep-core/tests/tainting_rules/js/metavar_eq_simple.js
> +
Oh I just saw the demos of matthew at the weekly-demos and now I see that we actually need to pass those source extra arguments ... Again could be nice to add comments in the test to explain those subtle things (basically what matthew said orally during his weekly-demo).

2021-10-27 11:42 UTC, IagoAbal commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +            let* xs = xs in
Note that you can move this up instead of duplicating it in each branch.

2021-10-27 11:49 UTC, IagoAbal commented on semgrep-core/tests/tainting_rules/js/metavar_eq_conditional.js
> +var source = cond ? get(A) : get(f(A))
If you really want to test that you get two matches on the same sink then you will need to use `pytest` (/semgrep/tests/) and use `$X` in the message so that the findings don't get deduplicated. Otherwise the test doesn't really test what you intend to test.

2021-10-27 17:21 UTC, minusworld commented on semgrep-core/tests/tainting_rules/js/metavar_eq_simple.js
> +
This example is a bit contrived, but illustrates a case where metavariable equality would be nice. The match on `f2.write(...)` I would expect not to be matched if the metavariables were equivalent: https://semgrep.dev/s/pYg0

2021-10-27 22:35 UTC, mmcqd commented on semgrep-core/src/engine/Dataflow_tainting.ml
> +(* @param env1 Metavariable environment.
Ok I switched to Iago's suggestion here

2021-10-27 22:37 UTC, mmcqd commented on semgrep-core/tests/tainting_rules/js/metavar_eq_conditional.js
> +var source = cond ? get(A) : get(f(A))
OK I made this test less subtle and explained how it's supposed to work in a comment. I'm not testing if a single sink is matched twice now. As you say the semgrep-core tests won't actually check for that, and semgrep won't even currently display both matches, so I think it's not essential to test for that right now.

2021-10-27 22:41 UTC, mmcqd commented on semgrep-core/tests/tainting_rules/js/metavar_eq_simple.js
> +
Added comments explaining the test. @minusworld's example here doesn't actually do what we want even with the PR because that `f2.write` is not between an `f2.write` and an `f2.close`, exactly as the rule specifies. If we change it to this: https://semgrep.dev/s/EvZL, it works even without the PR, because the important metavariable equality enforcement happens entirely within the sink rule. (said this on slack already but wanted to copy here in case someone reads this thread in the future).

2021-10-27 23:22 UTC, mmcqd commented on semgrep-core/tests/tainting_rules/js/metavar_eq_simple.js
> +
Going to mark this resolved and merge, but I created an issue to come up with a less contrived test on Linear (PA-601).

2021-10-27 23:23 UTC, merged