semgrep publish
semgrep/semgrep pull request #4687
Opened 2022-02-17 01:48 UTC by ievans

PR checklist:

- [ ] Documentation is up-to-date
- [ ] Changelog is up-to-date
- [ ] Change has no security implications (otherwise, ping security team)

2022-02-17 05:20 UTC, DrewDennison approved these changes

2022-02-17 21:56 UTC, brendongo requested changes
Can we add some tests for `semgrep publish` see https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/e2e/test_login.py that uses patches.

Error states to test: 
- upload w/o authentication
- upload with different badly formated yaml files(?)

IMO there might be a better command than publish? Since before this all semgrep use centered around findings so it might be confused with publishing findings? Thoughts on `semgrep upload-rule`?

2022-02-18 00:33 UTC, ievans commented
@brendongo done in https://github.com/returntocorp/semgrep/pull/4687/commits/bc0e90281cec51c89d1aa5050927c1e9893d177e

2022-02-18 04:38 UTC, brendongo commented
🔥 tests. Thanks @ievans !

2022-02-18 04:39 UTC, brendongo approved these changes

2022-02-18 06:46 UTC, merged