fix(auto): Add help line at the end of a scan with fingerprint information when using config auto
semgrep/semgrep pull request #4738
Opened 2022-02-25 20:34 UTC by minusworld

Fixes https://github.com/returntocorp/semgrep/issues/4674.

PR checklist:

- [ ] Documentation is up-to-date
- [ ] Changelog is up-to-date
- [ ] Change has no security implications (otherwise, ping security team)

2022-02-25 20:40 UTC, minusworld commented
Output looks like this.

With fingerprints:
```
Fetching rules from https://semgrep.dev/registry ...
Running 56 rules...
100%|████986/986 files

skipped: all .gitignored files, 2 files larger than 1.0 MB, 50 files matching .semgrepignore patterns
for a detailed list of skipped files, run semgrep with the --verbose flag

ran 56 rules on 718 files: 0 findings
(374 fingerprint findings. Run --config auto again in a few seconds to run new recommendations)
```

Without fingerprints:
```
[ ... ]
skipped: all .gitignored files, 2 files larger than 1.0 MB, 50 files matching .semgrepignore patterns
for a detailed list of skipped files, run semgrep with the --verbose flag

ran 135 rules on 268 files: 2 findings
```

2022-03-01 19:07 UTC, ievans commented on semgrep/semgrep/output.py
> +                auto_line = f"({num_fingerprint_findings} fingerprint findings. Run --config auto again in a few seconds to run new recommendations)"
```suggestion
                auto_line = f"({num_fingerprint_findings} fingerprint findings. Run --config auto again in a few seconds use new rule recommendations)"
```

2022-03-01 21:01 UTC, ievans requested changes
Can we have a test for this at all @minusworld ?

2022-03-02 20:27 UTC, minusworld commented
@ievans Added one, lmk what you think

2022-03-02 20:34 UTC, ievans approved these changes
looks great! Thanks @minusworld!

2022-03-02 23:56 UTC, merged