feat(swift): parsing for swift enums
semgrep/semgrep pull request #5870
Opened 2022-08-03 01:14 UTC by brandonspark

**What:**
Added functionality for parsing Swift enums into the generic AST.

**Why:**
I pulled up a random Swift repo on Github, and the first thing that failed was that we couldn't parse enums. It's probably a healthy reason for why our parse rate is so abysmal - imagine trying to parse a random OCaml project without `type`.

**How:**
I went and handled the TODOs.

It's worth noting that Swift has both C-style enums where each variant is just an alias for some base-type constant, _and_ ML-style sum types. The real terrible thing going on here is that they both use the `enum` syntax.

As such, I've just gone and flagged some base types as being "raw types", which indicate whether we should be parsing a "raw value enum", as detailed in the Swift docs (here)[https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html]. Thus, ahead of time, we determine whether to parse "raw" or "union", then go ahead and do that.

For raw-style enums, I've mostly followed how Java does them, in that each `enum` entry defines an `EnumEntryDef`. For instance:
```swift
enum Foo: Int {
  case a = 1
  case b
}
```
parses to
```
Pr(
  [DefStmt(
     ({
       name=EN(
              Id(("Foo", ()),
                {id_info_id=1; id_hidden=false; id_resolved=Ref(None); id_type=Ref(None); id_svalue=Ref(None); }));
       attrs=[KeywordAttr((EnumClass, ()))]; tparams=[]; },
      ClassDef(
        {ckind=(Class, ());
         cextends=[({t_attrs=[];
                     t=TyN(
                         Id(("Int", ()),
                           {id_info_id=2; id_hidden=false; id_resolved=Ref(
                            None); id_type=Ref(None); id_svalue=Ref(None); }));
                     },
                    None)];
         cimplements=[]; cmixins=[]; cparams=[];
         cbody=[F(
                  DefStmt(
                    ({
                      name=EN(
                             Id(("a", ()),
                               {id_info_id=3; id_hidden=false; id_resolved=Ref(
                                None); id_type=Ref(None); id_svalue=Ref(
                                None); }));
                      attrs=[]; tparams=[]; },
                     EnumEntryDef({ee_args=Some([Arg(L(Int((Some(1), ()))))]); ee_body=None; }))));
                F(
                  DefStmt(
                    ({
                      name=EN(
                             Id(("b", ()),
                               {id_info_id=4; id_hidden=false; id_resolved=Ref(
                                None); id_type=Ref(None); id_svalue=Ref(
                                None); }));
                      attrs=[]; tparams=[]; },
                     EnumEntryDef({ee_args=None; ee_body=None; }))))];
         })))])
```

Notably, this allows intermingling of regular fields with the actual enums themselves. This is intended.

For union-style enums... the syntax is confusing. It's weird because Swift allows its constructors to take in types, but they don't follow any first-class type in the language. Basically, each constructor takes in an ML record, but some of the fields don't need to have names... the closest solution I could get was a hodgepodge of ideas I took from CPP `AnonBitfield`s and regular sum types.

Basically, each constructor defines part of an `OrType`, which is an `OrConstructor`. The type that it takes in is not a straight product, but a `TyRecordAnd`, which may itself contain `DefStmt`s which are `FieldDefColon`s of the constituent type. If that field has a name, then the `DefStmt` entity just has that name, but if it's anonymous, then it is instead a `OtherEntity` named `AnonTupleField`. Here's an example of what I mean:
```swift
enum Foo {
  case a(Int, x: Int)
  case b
}
```
parses to
```
Pr(
  [DefStmt(
     ({
       name=EN(
              Id(("Foo", ()),
                {id_info_id=1; id_hidden=false; id_resolved=Ref(None); id_type=Ref(None); id_svalue=Ref(None); }));
       attrs=[KeywordAttr((EnumClass, ()))]; tparams=[]; },
      ClassDef(
        {ckind=(Class, ()); cextends=[]; cimplements=[]; cmixins=[]; cparams=[
         ];
         cbody=[F(
                  DefStmt(
                    ({
                      name=EN(
                             Id(("Foo", ()),
                               {id_info_id=5; id_hidden=false; id_resolved=Ref(
                                None); id_type=Ref(None); id_svalue=Ref(
                                None); }));
                      attrs=[]; tparams=[]; },
                     TypeDef(
                       {
                        tbody=OrType(
                                   [{t_attrs=[];
                                     t=TyRecordAnd((Class, ()),
                                            DefStmt(
                                              ({name=OtherEntity(("AnonTupleField", ()), []); attrs=[]; tparams=[]; },
                                               FieldDefColon(
                                                 {vinit=None;
                                                  vtype=Some({t_attrs=[
                                                              ];
                                                              t=TyN(
                                                                  Id((
                                                                    "Int", ()),
                                                                    {
                                                                    id_info_id=2; id_hidden=false;
                                                                    id_resolved=Ref(
                                                                    None); id_type=Ref(
                                                                    None); id_svalue=Ref(
                                                                    None); }));
                                                              });
                                                  }))));
                                          F(
                                            DefStmt(
                                              ({
                                                name=EN(
                                                       Id(("x", ()),
                                                         {id_info_id=3; id_hidden=false; id_resolved=Ref(
                                                          None); id_type=Ref(
                                                          None); id_svalue=Ref(
                                                          None); }));
                                                attrs=[]; tparams=[]; },
                                               FieldDefColon(
                                                 {vinit=None;
                                                  vtype=Some({t_attrs=[
                                                              ];
                                                              t=TyN(
                                                                  Id((
                                                                    "Int", ()),
                                                                    {
                                                                    id_info_id=4; id_hidden=false;
                                                                    id_resolved=Ref(
                                                                    None); id_type=Ref(
                                                                    None); id_svalue=Ref(
                                                                    None); }));
                                                              });
                                                  }))))]);
                                     }]); OrConstructor(("b", ()), [])]);
                        }))))];
         })))])
```

**Test plan:**
Look at the above, and check whether I'm doing stuff correctly.

Also, `ma [...]

2022-08-04 01:10 UTC, nmote commented
I'm not clear on the reason for splitting up parsing into two different modes. Could you provide specifics on the undesirable outcome that would occur if we were to parse enum declarations on a best effort basis without having this context?

2022-08-04 21:48 UTC, brandonspark commented
> I'm not clear on the reason for splitting up parsing into two different modes. Could you provide specifics on the undesirable outcome that would occur if we were to parse enum declarations on a best effort basis without having this context?

Well, doing it on a best effort basis results in messier code, I feel.

The problem is that depending on which mode we're in, we both modes support something like `case a;`. Now, in a union-style enum, this is simply a constructor `a` which takes no arguments. In a raw-style enum, this is instead a case of the enum which is initialized to one plus the previous raw value enum variant, or a default value if it is the first.

Semantics aside, syntactically this presents an issue because we don't know if we should parse it as an `EnumEntryDef`, or if we should go save it and put it inside of an `OrType`. We could scout ahead and look at the enum's contents to see whether it is used as a raw style or union-style, but that doesn't stop us from partitioning our code's behavior here. We could simply parse however we feel like, but if we start parsing it as a raw style, for instance, once we see a `case a(Int)` we're going to need to go back and remove the previous instances of `EnumEntryDef` that we put.

It just seems cleaner and like the least amount of code duplication to split the code flow early based on a clear indicator that we're given.

2022-08-16 18:27 UTC, nmote requested changes
Overall this looks good! I do have several requests which I made inline that I'd like you to address before merging, but this is great progress towards experimental Swift support!

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      |> G.s)
Makes sense. Could you add an explanation similar to what you said in the PR summary as a comment here?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
>    (* TODO include captures *)
Remove this TODO

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/Test_parsing.ml
> +module SMap = Map.Make (String)
The changes to this file seem unrelated. Could you move these into a separate PR so that they can be reviewed separately?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      G.unhandled_keywordattr ("Prefix", token env tok)
Instead of writing out the string yourself, `str env tok` should get you the pair of string and parse info that you need here.

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      G.unhandled_keywordattr ("UnownedUnsafe", token env tok)
Look into the `str` helper for this too

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      | Some { G.e = _; _ } -> raise Common.Impossible
Can you provide a stronger justification for why this is impossible? Maybe the grammar is overly permissive and Swift doesn't actually allow this, in which case a link to the spec or at least a specific code snippet that Swift rejects in practice?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      | Some { G.e = _; _ } -> raise Common.Impossible
Same here

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      G.unhandled_keywordattr ("Required", token env tok)
`str` helper here too

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      G.unhandled_keywordattr ("Nonmutating", token env tok)
`str` here too

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      G.unhandled_keywordattr ("Class", token env tok)
and here

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +      G.unhandled_keywordattr ("Autoclosure", token env tok)
and here

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +        map_referenceable_operator env x |> fst |> fun x -> (PI.str_of_info x, x)
We probably shouldn't be using `str_of_info` here. Maybe you can pass the original string up from `map_referenceable_operator` instead? Once again, the `str` function will let you extract that from the original CST token.

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +        (PI.str_of_info tok, tok)
Same here

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +  (* This does not seem important semantically. *)
If you're going to make this claim, could you justify it?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +  let attrs = v1 @ [ G.unhandled_keywordattr ("Get", v2) ] in
`str`

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +   *)
What?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +   *)
Again, what?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +  let attrs = v1 @ [ G.unhandled_keywordattr ("Modify", v2) ] in
`str`

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +   *)
Same

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +  let attrs = v1 @ [ G.unhandled_keywordattr ("Set", v2) ] in
`str`

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +  *)
Is this comment out of date?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +    cond conds
We've discussed this separately, but could you add a comment here justifying this desugaring?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +(* This is a misleading name, it has nothing to do with the lambda's type... *)
What is it instead?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +              let _todo = map_simple_identifier env x in
Just pipe this to `todo env` so that it doesn't get overlooked if we encounter this?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +        let _todo = token env tok in
Pipe this to `todo env` so that it doesn't get overlooked if we do encounter it?

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +              [ G.unhandled_keywordattr ("Indirect", token env tok) ]
`str`

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +          H2.name_of_id ("ConformsTo", v3),
Probably better to use the string in the original program text via `str` even though it's just a colon.

2022-08-16 18:27 UTC, nmote commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +          H2.name_of_id ("EqualTypes", v3),
Same here

2022-08-16 22:28 UTC, brandonspark commented on semgrep-core/src/parsing/tree_sitter/Parse_swift_tree_sitter.ml
> +  *)
yes!

2022-08-16 23:23 UTC, nmote approved these changes
Nice! Looking forward to seeing this bump the Swift parsing stats!

2022-08-16 23:23 UTC, merged