feat: parsing todo statistics
semgrep/semgrep pull request #5929
Opened 2022-08-16 22:57 UTC by brandonspark

**What:**
It's real rough when you're trying to add a new language to Semgrep. There's like a billion TODOs around, and you gotta fix all of them. The thing is though, although we can get parsing statistics as to what files we have difficulty parsing, and our percentage of parse rate, they aren't actually directed towards where in the translation process that we failed; they just say that we failed.

This PR adds parsing TODO statistics, which count up the places where `todo` was called from within the parser, and then reports them in descending order. That way, you can focus on TODOs which are more prevalent, and make changes which have maximal impact in getting parse rate up.

**Why**:
We should be able to write translations in a more directed fashion, prioritizing those parts of the language which are most common.

**How:**
I parse the exception backtrace for each failed test, for the first instance of a non-`todo`-named function. I save the line number too. Then, I concatenate them together, and order them in descending order, and print to the relevant `stats.log` file. This hooks into the `./run-lang <lang>` parse rate estimator.

So, for instance, with our current 2% parse rate Swift parser, I ran the `./run-lang swift` command, and then the end of the `stats.log` that is produced has the following:

```
TODO statistics:

Parse_swift_tree_sitter.map_non_local_scope_modifier:302, -> 133
Parse_swift_tree_sitter.map_attribute:790, -> 26
Parse_swift_tree_sitter.map_value_argument:2931, -> 10
Parse_swift_tree_sitter.map_call_expression:927, -> 9
Parse_swift_tree_sitter.map_property_declaration:2281, -> 4
Parse_swift_tree_sitter.map_binding_pattern_with_expr:890, -> 3
Parse_swift_tree_sitter.map_type_constraints:2719, -> 2
Parse_swift_tree_sitter.map_type_arguments:2687, -> 1
```
This tells us that the largest source of parse errors is on line 302 in `map_non_local_scope_modifier`, tripping a whole 133 times. This means that we should fix that one next, in order to get parse rate up.

PR checklist:

- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] `changelog.d/<issue>.<type>` is a file with the _what_, _why_, and _how_ of the change.
  - \<issue> is `pa-312` (Linear ticket), `gh-1234` (GitHub issue), or `new-gizmo` (unique semantic name)
  - \<type> is `added`, `changed`, `fixed`, or `infra`.
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Changelog guidelines](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry)
- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2022-08-17 15:40 UTC, nmote requested changes
Nice, this will help quite a bit. I used a similar tactic when working to get PHP parse errors up, but it was a little more ad-hoc.

One request, though -- could you either change it so that it only prints this information when JSON output was not requested, or double-check that it won't interfere with whatever consumes that info? This is printed on stderr and the JSON is on stdout, it looks like, so it should be fine, but I'd be happier if you took a quick look at how the output here is consumed.

2022-08-17 20:30 UTC, brandonspark commented
> Nice, this will help quite a bit. I used a similar tactic when working to get PHP parse errors up, but it was a little more ad-hoc.
> 
> One request, though -- could you either change it so that it only prints this information when JSON output was not requested, or double-check that it won't interfere with whatever consumes that info? This is printed on stderr and the JSON is on stdout, it looks like, so it should be fine, but I'd be happier if you took a quick look at how the output here is consumed.

It looks like the `run-lang` script only ever calls `semgrep-core` with the `-json` flag, so if I make it so that it only prints when JSON is not requested, it will never print.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/49291449/185236910-f304a014-cb78-4106-921a-8414360d16ee.png">

It looks like stderr is specifically piped to the `.log`, and `.json` for the stdout. I don't believe that they should interfere, given that we are using `print_endline` for `print_json` and `pr2` for `report_counts`. Let me know if I should look into it more, though.

2022-08-17 20:58 UTC, nmote approved these changes
Sounds good, thanks for checking into it!

2022-08-18 03:39 UTC, merged

2022-08-18 13:13 UTC, aryx reviewed
This is great! We should probably update https://semgrep.dev/docs/contributing/adding-a-language/
and let external contributors (or a new PA hire, or me in 6 months) know about this!

2022-08-18 13:13 UTC, aryx commented on semgrep-core/src/parsing/Test_parsing.ml
> +        (* Sue me. I don't want to write a real lexer and parser. *)
I usually use a regexp.
if s =~ "Called from \\([^ ]+\\) in [^ ]+ line \\([0-9]+\\)"
then
  let (funcname, line) = Common.matched2 s in
 ...

2022-08-18 13:13 UTC, aryx commented on semgrep-core/src/parsing/Test_parsing.ml
> +   I'm using maps to do this so that I can achieve O(log n) insertion per increment.
I usually just use a Hashtbl and then Common.hash_to_list |> Common.sort_by_value |> Common.take_safe 10 |> ...