add(error): exit gracefully if running on linux arm64
semgrep/semgrep pull request #6313
Opened 2022-10-13 15:42 UTC by brendongo

PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2022-10-13 15:50 UTC, brendongo commented
Not really sure how to easily test this since looks like github action runners are all x86 based. Maybe running in a docker image?

2022-10-13 15:52 UTC, bmahe requested changes
Can we add a changelog entry?

2022-10-13 15:55 UTC, DrewDennison approved these changes

2022-10-13 16:13 UTC, brendongo commented
Tested locally by building: 
```
FROM arm64v8/python:3.10-alpine

WORKDIR /semgrep

#???
ENV PIP_DISABLE_PIP_VERSION_CHECK=true \
    PIP_NO_CACHE_DIR=true \
    PYTHONIOENCODING=utf8 \
    PYTHONUNBUFFERED=1

RUN apk add --no-cache --virtual=.run-deps\
     bash git git-lfs openssh libstdc++

COPY cli ./
RUN apk add --no-cache --virtual=.build-deps build-base make g++ &&\
     pip install jsonnet &&\
     SEMGREP_SKIP_BIN=true pip install /semgrep &&\
     semgrep --version &&\
     apk del .build-deps &&\
     mkdir -p /tmp/.cache

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY Dockerfile /Dockerfile

ENV SEMGREP_IN_DOCKER=1 \
    SEMGREP_VERSION_CACHE_PATH=/tmp/.cache/semgrep_version \
    SEMGREP_USER_AGENT_APPEND="Docker"

WORKDIR /src

RUN rm -rf /semgrep

ENTRYPOINT ["/entrypoint.sh"]
CMD ["semgrep", "--help"]
LABEL maintainer="support@r2c.dev"
```
and it exits gracefully with error message

2022-10-14 01:34 UTC, bmahe approved these changes

2022-10-20 07:13 UTC, aryx approved these changes

2022-10-20 07:13 UTC, merged