fix(cli): separate experimental rules in `--debug`
semgrep/semgrep pull request #6531
Opened 2022-11-15 23:26 UTC by brandonspark

## What:
Currently, the `semgrep --debug` output displays a list of all the rules that have been run. Experimental rules are not displayed differently, however, which can be confusing to people who are running experimental rules, but are unaware.

## Why:
We should fix this so `semgrep` is more clear about experimental rules and when they are run.

## How:
Separated out experimental rules in the `--debug` output. Added some tests.

## Test plan:
`make test`

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2022-11-16 00:15 UTC, brendon commented
Wrong @brendon ;)

2022-11-17 17:34 UTC, brendongo commented on cli/tests/e2e/snapshots/test_check/test_max_memory/error.txt
> +Experimental Rules:
Maybe don't print this out if there are no experimental rules?

2022-11-18 18:49 UTC, brendongo requested changes
see above

2022-11-22 01:18 UTC, brandonspark commented on cli/tests/e2e/snapshots/test_check/test_max_memory/error.txt
> +Experimental Rules:
fair. i was giong off the fact taht `Rules` is printed even if there are none, but i realize that this is probably a much more likely occurrence

2022-11-28 16:35 UTC, brandonspark commented
@brendongo any thoughts?

2022-12-01 00:38 UTC, brendongo approved these changes

2022-12-03 07:52 UTC, merged