feat(schema): update rule schema for new syntax
semgrep/semgrep pull request #6601
Opened 2022-11-23 23:39 UTC by brandonspark

## What:
A while ago Cooper and I did #5916, which added new pattern syntax. This works for `semgrep-core`, but is rejected by `semgrep`, because it doesn't align with the rule schema. I've been procrastinating merging the rule schema PR for months, but it's high time SR got to use the new shiny syntax.

## Why:
SR should use the shiny new syntax!!!

## How:
Merged the `semgrep-interfaces` PR, and upgraded it (and some tests) here. I didn't add a changelog because I don't consider this user-facing.

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2022-11-28 15:09 UTC, aryx requested changes
let's wait until we release 1.0 this week.

2022-12-06 05:50 UTC, brandonspark commented
@aryx revisit?

2022-12-08 13:33 UTC, aryx approved these changes

2022-12-08 13:33 UTC, aryx commented
just have to merge develop and this should solve the conflict.

2022-12-12 18:00 UTC, merged