Check whether semgrep-proprietary still builds
semgrep/semgrep pull request #6603
Opened 2022-11-24 07:01 UTC by mjambon

See description in the job config.

PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2022-11-24 07:25 UTC, mjambon commented
The alpine image we use doesn't come with `ssh` or with `gh`. We can run `apk add openssh` but what about `gh`? It would need to be installed from a tarball as described [here](https://github.com/cli/cli/issues/658#issuecomment-701375745). It's not a huge deal but I'd like to know if there's a way to post a PR comment without installing `gh` into our docker container.

2022-11-28 17:31 UTC, spencerdrak requested changes
Overall, this looks good, but there's three comments I have:
- I think it would be best to wait until after we reelase 1.0.0 to merge this in, so our release process freeze has ended
- The auth (as noted) might need some work. LMK if you need some help with that
- I would strongly suggest testing this in our test GH Actions repository. I am happy to explain how that works, or even better, I can find some time to put together a better set of documents around that. I'll touch base when I get those into Notion.

2022-11-28 17:31 UTC, spencerdrak commented on scripts/build-semgrep-proprietary
> +  git clone "$semgrep_pro_url" --depth 1
I think auth might need to be configured here, since `semgrep-proprietary` is a private repo.

2023-05-02 12:58 UTC, aryx commented
Closing; Someone can reopen when it works.
It just clutters our list of pull requests. We must keep it clean.

2023-05-02 12:58 UTC, closed without merging