Brandon/fix yaml target metavariable parsing
semgrep/semgrep pull request #6656
Opened 2022-12-03 08:26 UTC by brandonspark

## What:
Currently, our YAML parser parses metavariables strangely in target files. Because the YAML pattern parser has to be able to use Semgrep metavariables, and the target parser is the same parser, it results in metavariables resulting in the target Generic AST. This causes issues with matching, where metavariables in YAML rules which match ranges that look like metavariables will end up with content that is just the empty string. 

This can be observed at the following Playground link (see the message): https://semgrep.dev/playground/s/brandonspark:yaml-metavariable-matching-metavariable

## Why:
This just doesn't make sense. We should be able to match the metavariable with the metavariable.

## How:
I added a flag to the YAML parser so it is aware of if we are parsing a target. If we are parsing a target, then it should treat metavariables it sees as strings.

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2022-12-08 13:46 UTC, aryx requested changes

2022-12-08 13:46 UTC, aryx commented on semgrep-core/src/osemgrep/cli_scan/Rule_fetching.ml
> +  let gen = Yaml_to_generic.program ~is_target:false file in
this should be true

2022-12-08 13:46 UTC, aryx commented on semgrep-core/src/parsing/Parse_rule.ml
> +    | FT.Config FT.Yaml -> parse_yaml_rule_file ~is_target:false file
this should be true

2022-12-08 13:46 UTC, aryx commented on semgrep-core/src/parsing/other/yaml_to_generic.mli
> +val program : is_target:bool -> Common.filename -> AST_generic.program
I don't think you need a label. When we use the program function, it's a target,
when we use any, it's always to parse a pattern.

2022-12-12 19:43 UTC, aryx approved these changes

2022-12-12 19:43 UTC, aryx commented on semgrep-core/src/parsing/Parse_rule.ml
> +    | FT.Config FT.Yaml -> parse_yaml_rule_file ~is_target:false file
Why did you continue to use false?
We're parsing a rule, so the rule will not contain metavariables; only the patterns inside the rule will, but that's using a different function (Parse_pattern).

2022-12-12 19:55 UTC, merged

2022-12-13 10:29 UTC, IagoAbal commented
Bad idea to use mutable links like https://semgrep.dev/playground/s/brandonspark:yaml-metavariable-matching-metavariable in GitHub issues, better immutable ones: https://semgrep.dev/s/kKJ2.

2022-12-13 10:34 UTC, IagoAbal commented on semgrep-core/src/parsing/other/yaml_to_generic.mli
> +   `program` and `any` will behave slightly differently on metavariables.
I understand this comment now, but in X months I probably don't. Some of the explanation that went into the PR comment should probably go here too.