feat(ojsonnet): desugar array comprehensions and eval specials
semgrep/semgrep pull request #6668
Opened 2022-12-06 22:44 UTC by brandonspark

## What:
Adds in desugaring of array comprehensions. Also adds in evaluation of some specials I added.

## Why:
Need it to make `ojsonnet`'s semantics work

## How:
I added two specials, `StdMakeArray` and `StdLength`, which are base functions whose semantics are given in the operational semantics. These are then cased on in `Eval_jsonnet`, which I also implemented the big-step dynamics of.

For the generation of fresh variable names, I just picked an unlikely variable name and appended increasing numbers to it. I realize this is disgusting, but in practice it will never come up. C'mon. Should have used de Bruijn indices if you didn't want me to do that.

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2022-12-08 10:07 UTC, aryx commented
test plan?

2022-12-08 10:21 UTC, aryx requested changes

2022-12-08 10:21 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Core_jsonnet.ml
> +and special = Self | Super | StdLength | StdMakeArray
Why not using the Desugar_jsonnet.mk_DotAccess_std to generate those calls?

2022-12-08 10:21 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Desugar_jsonnet.ml
> +    ("reallylongfreshvariablename" ^ string_of_int !store, fk)
you can use something like "!tmp!"
it's guaranteed to not conflict with a variable from the program since !tmp! is not a valid identifier.

2022-12-08 10:21 UTC, aryx commented on semgrep-core/src/ojsonnet/parsing/AST_jsonnet.ml
> +  (* ??? *)
I'm not convinced. Those things are not in the grammar, and are not in the Core jsonnet definitions in the spec.
I'd rather follow closely the spec and use the mk_DotAccess_std function I've defined.

2022-12-08 10:21 UTC, aryx commented on semgrep-core/src/ojsonnet/parsing/AST_jsonnet.ml
> +  (* ??? *)
In fact, where do you build AST trees containing AST_jsonnet.stdMakeArray? Nowhere ... the Parse_jsonnet_tree_sitter.ml does not build them (and it should not).

2022-12-08 10:21 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Desugar_jsonnet.ml
> +and desugar_comprehension_helper env expr comps =
can you put the return type for this function like I did for desugar_expr (the original code was autogenerated by otarzan so when you "fill it" with the correct code, it can be useful to add type annotations, which otarzan can't add).

2022-12-08 10:21 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Eval_jsonnet.ml
> +  | Call (IdSpecial (StdLength, _), (_l, args, _r)) ->
I think that if you remove those StdXxx specials and just use mk_DotAccess_Std, you
can intercept instead at Call (ArrayAccess(Id "std", Id "length")) ...

2022-12-08 10:21 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Desugar_jsonnet.ml
> +        Call (DotAccess (Id ("std", fk), fk, ("join", fk)), fb [ Arg l; Arg r ])
use mk_DotAccess_Std

2022-12-12 17:59 UTC, brandonspark commented on semgrep-core/src/ojsonnet/parsing/AST_jsonnet.ml
> +  (* ??? *)
i was relying on `Desugar` to produce them, but you're correct that it shouldn't have been a new variant

2022-12-14 11:01 UTC, aryx approved these changes
I'll approve because it's good progress, but I think you need to fix the "this is wrong"
or put a TODO and fix it in another PR.

2022-12-14 11:01 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Desugar_jsonnet.ml
>        todo env v
We probably don't want to return a todo here.
BTW what is your test plan for your PR?

2022-12-14 11:01 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Desugar_jsonnet.ml
> +  | CompIf (tok, cond) :: rest ->
I tried to use the same name than in the spec, so for example here I would use e' instead of cond,
so it really matches the spec, and I would rename the passed expr parameter as 'e', like in the spec.

2022-12-14 11:01 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Desugar_jsonnet.ml
> +  | CompFor (_, x, _, for_expr) :: rest ->
I would use e' instead of for_expr, to follow the spec

2022-12-14 11:01 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Eval_jsonnet.ml
> +          Primitive (Double (float_of_int (List.length args), fk))
This is wrong. You need to inspect args, which should always have one element, then evaluate it,
then look at its type, and depending on its type (string, array, object) do different things.

2022-12-14 11:01 UTC, aryx commented on semgrep-core/src/ojsonnet/interpreting/Eval_jsonnet.ml
> +      | _ -> failwith "impossible: invalid program in dynamics")
This is wrong too. If the method is not length, or makeArray, then we should default to the normal
evaluation of Call, because those methods should be defined in the imported std.jsonnet.

2022-12-14 13:38 UTC, aryx commented
hmm, I need the code in this PR so I'll add myself the TODO in another PR and try to improve on it.

2022-12-14 13:38 UTC, merged