use Brewfile to avoid already installed warnings
semgrep/semgrep pull request #700
Opened 2020-05-06 16:54 UTC by stephengroat

2020-05-06 17:15 UTC, DrewDennison reviewed
Very cool!

2020-05-07 02:53 UTC, stephengroat commented
seems like the ocaml opam cert is out of date, waiting until it works

<img width="864" alt="Screen Shot 2020-05-06 at 7 52 44 PM" src="https://user-images.githubusercontent.com/1159138/81249357-3b100b00-8fd3-11ea-96f7-12c4bbcee808.png">

2020-05-07 06:24 UTC, DrewDennison commented
@stephengroat yeah that just broke all our builds lol. Hopefully it gets fixed tomorrow.

2020-05-07 15:56 UTC, ievans commented
@DrewDennison looks like this is passing, just can't push the docker tag to our registry from the fork.

2020-05-07 16:53 UTC, DrewDennison commented
@stephengroat cert got fixed! I I'm happy to merge

2020-05-07 17:07 UTC, brendongo commented on .github/workflows/mac-build.yml
> +          git remote set-url origin https://github.com/darlinghq/darling.git
Why are we setting url to darling?

2020-05-07 17:37 UTC, brendongo commented on .github/workflows/mac-build.yml
> +      - name: Install Brewfile
We should just call the osx-release script.

2020-05-07 17:37 UTC, brendongo requested changes
See comments above

2020-05-19 17:27 UTC, brendongo commented
Closing due to inactivity. @stephengroat feel free to reopen.

2020-05-19 17:27 UTC, closed without merging