fix(rule parsing perf): initial changes to speed up rule parsing
semgrep/semgrep pull request #7188
Opened 2023-02-18 20:37 UTC by emjin

Rule parsing is slow because we create and remove a tmp file for each pattern we parse. This is entirely unnecessary; the Lexer class supports lexing strings. While rule parsing is a relatively small amount of time compared to full scans, it is relatively large compared to diff scans or scans of small repos, which affects the feel of semgrep. Also, I am just morally against creating unnecessary tmp files.

TODO: ruby rule parsing is still really slow; it's more complicated so I haven't yet gone and changed its parsing code

TODO: if rule parsing is still a few seconds long after these changes, we can additionally filter out rules that aren't relevant to the files passed.

Test plan: make test, also time with running p/default on a single file

On p/python this dropped runtime with a small test from 2.4 seconds to 0.5 seconds

PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-02-18 20:44 UTC, emjin commented
Develop:
```
============================[ summary ]============================
Total time: 46.9369s Config time: 2.3474s Core time: 44.5413s

Semgrep-core time:
Total CPU time: 97.2311s  File parse time: 62.3313s  Rule parse time: 22.4738s  Match time: 25.7200s
Slowest 5/1498 files
libs/spacegrep/examples/my_first_calculator.py.doc (753KB): 6.428s (5.563s to parse)
src/engine/Entropy_data.ml                         (329KB): 2.999s (3.619s to parse)
perf/perf-matching/input/l5000.java                (487KB): 0.719s (3.374s to parse)
perf/perf-matching/input/l10000.js                 (203KB): 14.487s (3.234s to parse)
libs/commons/common2.ml                            (164KB): 0.818s (1.717s to parse)
Slowest 5 rules to match
...skip-tls-verify-service.skip-tls-verify-service:         0.000s
...skip-tls-verify-cluster.skip-tls-verify-cluster:         0.000s
...nfinement-disabled.seccomp-confinement-disabled:         0.000s
...rnetes.security.run-as-non-root.run-as-non-root:         0.000s
...urity.privileged-container.privileged-container:         0.000s

Analyzed: 13 bash files ( 12KB in 0.018 seconds)
          4 c files ( 21KB in 0.021 seconds)
          3 dockerfile files (  9KB in 0.004 seconds)
          422 generic files (  3MB in 10.626 seconds)
          1 go files ( 53KB in 0.018 seconds)
          1 java files (487KB in 0.719 seconds)
          7 js files (225KB in 15.721 seconds)
          9 json files (489KB in 0.114 seconds)
          1 jsonnet files (  4KB in 0.002 seconds)
          766 ocaml files (  6MB in 13.655 seconds)
          235 python files (  1MB in 33.392 seconds)
          36 yaml files (130KB in 0.467 seconds)
Errors:   16 files with errors, see output before the results for details or run with --strict
          PartialParsing (16 files)
                                                                                                                        
                                                                                                                        
┌──────────────┐                                                                                                        
│ Scan Summary │                                                                                                        
└──────────────┘                                                                                                        
                                                                                                                        
Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Partially scanned: 16 files only partially analyzed due to a parsing or internal Semgrep error
  Scan skipped: 19 files larger than 1.0 MB, 4694 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1413 rules on 1498 files: 46 findings.

A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading
semgrep --config p/default --time  192.28s user 14.35s system 337% cpu 1:01.23 total
```

My branch:
```
============================[ summary ]============================
Total time: 34.8775s Config time: 2.4688s Core time: 32.3112s

Semgrep-core time:
Total CPU time: 85.0090s  File parse time: 55.1258s  Rule parse time: 13.9053s  Match time: 22.6858s
Slowest 5/1498 files
libs/spacegrep/examples/my_first_calculator.py.doc (753KB): 6.314s (5.345s to parse)
src/engine/Entropy_data.ml                         (329KB): 2.543s (2.993s to parse)
perf/perf-matching/input/l5000.java                (487KB): 0.557s (2.772s to parse)
perf/perf-matching/input/l10000.js                 (203KB): 12.245s (2.703s to parse)
libs/commons/common2.ml                            (164KB): 0.039s (1.440s to parse)
Slowest 5 rules to match
...skip-tls-verify-service.skip-tls-verify-service:         0.000s
...skip-tls-verify-cluster.skip-tls-verify-cluster:         0.000s
...nfinement-disabled.seccomp-confinement-disabled:         0.000s
...rnetes.security.run-as-non-root.run-as-non-root:         0.000s
...urity.privileged-container.privileged-container:         0.000s

Analyzed: 13 bash files ( 12KB in 0.014 seconds)
          4 c files ( 21KB in 0.033 seconds)
          3 dockerfile files (  9KB in 0.014 seconds)
          422 generic files (  3MB in 9.357 seconds)
          1 go files ( 53KB in 0.242 seconds)
          1 java files (487KB in 0.557 seconds)
          7 js files (225KB in 13.642 seconds)
          9 json files (489KB in 0.166 seconds)
          1 jsonnet files (  4KB in 0.001 seconds)
          766 ocaml files (  6MB in 12.009 seconds)
          235 python files (  1MB in 34.650 seconds)
          36 yaml files (130KB in 0.418 seconds)
Errors:   17 files with errors, see output before the results for details or run with --strict
          PartialParsing (17 files)
                                                                                                                        
                                                                                                                        
┌──────────────┐                                                                                                        
│ Scan Summary │                                                                                                        
└──────────────┘                                                                                                        
                                                                                                                        
Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Partially scanned: 17 files only partially analyzed due to a parsing or internal Semgrep error
  Scan skipped: 19 files larger than 1.0 MB, 4694 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1413 rules on 1498 files: 46 findings.

A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading
semgrep --config p/default --time  179.26s user 9.67s system 390% cpu 48.328 total
```

2023-02-22 10:15 UTC, aryx approved these changes
This is great. Thx for fixing that!
But just please choose a better name than parsed_value ...

2023-02-22 10:15 UTC, aryx commented on libs/lib_parsing/Parse_info.ml
> +[@@deriving show, eq]
hmm, I'd rather remove eq, so that people don't use equality on tokens, which they should not need.
(for example in AST_generic we don't care about tokens for equality, we abstract away tokens).

2023-02-22 10:15 UTC, aryx commented on libs/lib_parsing/Parsing_helpers.ml
> +type parsed_value = Str of string | File of Common.filename
how is that a parsed value?
It's not parsed ...
Do you mean maybe target? or target_kind?

2023-02-22 10:15 UTC, aryx commented on libs/lib_parsing/Parsing_helpers.ml
> +let full_charpos_to_pos_str s =
add a comment like
(* this is mostly a copy-paste of full_charpos_to_pos_large below, but using a string for the target instead of a file *)

2023-02-22 10:15 UTC, aryx commented on libs/lib_parsing/Parsing_helpers.ml
> +type parsed_value = Str of string | File of Common.filename
If you feel in a good mood, maybe you can replace Common.filename by Fpath.t here.
(Then you need to use at a few places Fpath.v, and Fpath.to_string to convert back and forth).

2023-02-22 10:15 UTC, aryx commented on cli/tests/e2e/snapshots/test_output/test_debug_experimental_rule/results.txt
> -<MASKED>
?? Why this is in this PR?

2023-02-22 10:15 UTC, aryx commented on languages/ocaml/menhir/parse_ml.ml
> +  let toks = tokens (Parsing_helpers.File filename) in
Please rename the argument to the tokens function above too from 'file' to 'target' (or 'target_kind')

2023-02-22 10:15 UTC, aryx commented on languages/php/menhir/parse_php.ml
> + fun str -> tokens (Parsing_helpers.Str str)
hmm I'm surprised the tests are passing, but I think you'll need to also add the leading
<?php to str before calling tokens.

2023-02-22 10:15 UTC, aryx commented on libs/lib_parsing/Parse_info.ml
> +[@@deriving show, eq]
In fact, why do you need show and eq in this PR?

2023-02-23 15:50 UTC, emjin commented on libs/lib_parsing/Parse_info.ml
> +[@@deriving show, eq]
I added this to debug and left it in because it was useful to me. Can delete!

2023-02-23 15:51 UTC, emjin commented on cli/tests/e2e/snapshots/test_output/test_debug_experimental_rule/results.txt
> -<MASKED>
One of the lines used to say `Deleting /var/folders/..../tmp....`, but we no longer log it!

2023-02-24 13:03 UTC, aryx requested changes

2023-02-24 13:03 UTC, aryx commented on libs/lib_parsing/Parsing_helpers.ml
> +type input_stream = Str of string | File of Common.filename
Still not a good name. An input_stream would be a stream of tokens, like in the stream.mli standard library.
In spacegrep/.../Src_file.mli there is:
```
(*
   A representation of the input document, used to recover code snippets
   from locations.
*)

type t
type source = File of string | Stdin | String | Channel
```
so maybe we could also call it input_source, or input_kind

2023-02-25 19:57 UTC, emjin commented on libs/lib_parsing/Parsing_helpers.ml
> +type input_stream = Str of string | File of Common.filename
I like input_source

2023-02-26 10:11 UTC, aryx approved these changes

2023-02-26 10:11 UTC, merged