new CI job: build from empty opam switch
semgrep/semgrep pull request #7417
Opened 2023-03-29 11:13 UTC by hannesm

To uncover issues such as "missing package uri".

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-03-29 11:48 UTC, aryx requested changes

2023-03-29 11:48 UTC, aryx commented on .github/workflows/build-from-empty-opam.yaml
> +name: Build from empty opam switch
Maybe add a comment on why we need this workflow, explaining the example
we had with uri and the fact that some errors are hidden because of our use of ocaml-layer.

2023-03-29 12:06 UTC, hannesm commented on .github/workflows/build-from-empty-opam.yaml
> +name: Build from empty opam switch
done in [1bd49b1](https://github.com/returntocorp/semgrep/pull/7417/commits/1bd49b18b3ca9b5070b39b416fd77c3674fd3cfd)

2023-03-29 12:13 UTC, aryx approved these changes

2023-03-29 12:17 UTC, aryx commented
CI failure:
```
/home/runner/work/_actions/ocaml/setup-ocaml/v2/dist/index.js:4645
        throw new Error(`Input required and not supplied: ${name}`);
        ^
```

2023-03-30 09:03 UTC, aryx commented
not sure what's going on, but it takes more than 14min already to just get OCaml 4.14.

2023-03-30 13:15 UTC, dinosaure commented
This PR was replaced by #7425 - I don't have the right to (force) push into the @hannesm's repository.

2023-03-30 13:51 UTC, aryx commented on .github/workflows/build-from-empty-opam.yaml
> +        ocaml-version: ["4.14.x"]
ok, romain changed this 4.14.x to 4.14.0
weird that it was causing the CI job to take forever.

2023-03-30 13:52 UTC, closed without merging