feat(scala): parse unparenthesized conditions in `if`, `while`
semgrep/semgrep pull request #7480
Opened 2023-04-07 23:13 UTC by brandonspark

## What:
This PR lets us parse conditions without parens in `if` and `while`, which is a thing in Scala 3.

## Why:
Parse rate.

## How:
Added two cases.

## Test plan:
`make test`
Parse rate goes to `0.9589261173709144` from `0.9570153111528416`

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-04-12 08:15 UTC, aryx requested changes

2023-04-12 08:15 UTC, aryx commented on languages/scala/ast/AST_scala.ml
> +  | EnumClass (* for enum classes *)
this should be not be part of this PR. It has nothing to do with the title

2023-04-12 09:48 UTC, aryx approved these changes

2023-04-12 09:49 UTC, merged

2023-04-17 16:17 UTC, brandonspark commented on languages/scala/ast/AST_scala.ml
> +  | EnumClass (* for enum classes *)
same as before