feat(scala): parse indented `for` exprs
semgrep/semgrep pull request #7496
Opened 2023-04-11 20:39 UTC by brandonspark

## What:
This PR makes it so we can parse `for` expressions whose enumerators are indented, as opposed to wrapped in braces/parens.

## Why:
Parse rate.

## How:
Cased on if it was in a braces or parens. If not, it's assumed to be indented, so we just call `enumerators` directly.

I deliberately did not call `inBracesOrIndented`, because entering the indentation region of the `for` will mess us up at the end, when determining when to end the `enumerators`. This is because we will see a `DEDENT`, but because of the way the code is structured, this will make it difficult to properly have the tokens synchronized properly when we break out of the enumerators sequence.

This is similar to what the Scala compiler does: https://github.com/lampepfl/dotty/blob/865aa639c98e0a8771366b3ebc9580cc8b61bfeb/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L2730

Closes PA-2695

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-04-12 06:56 UTC, IagoAbal commented on languages/scala/recursive_descent/Parser_scala_recursive_descent.ml
> +        fb (PI.unsafe_fake_info "") (enumerators in_)
Can we not use unsafe fake tokens here? The `unsafe_` is meant to flag that it shouldn't be abused. In this case we have some token around readily available to create a "safe" fake token.

2023-04-12 06:59 UTC, IagoAbal approved these changes
Looks good to me, but I'm not familiar with this parser.

2023-04-12 08:54 UTC, aryx requested changes

2023-04-12 08:54 UTC, aryx commented on changelog.d/pa-2694.added
> +Scala: Can now parse top-level definitions (as added in Scala 3)
this should not be part of this PR

2023-04-12 08:54 UTC, aryx commented on languages/scala/ast/AST_scala.ml
> +  | Opaque
This should not be in this PR.

2023-04-12 09:44 UTC, aryx approved these changes

2023-04-12 09:44 UTC, merged

2023-04-17 16:16 UTC, brandonspark commented on changelog.d/pa-2694.added
> +Scala: Can now parse top-level definitions (as added in Scala 3)
i suspect it was not, but the merge base probably changed due to all the stacked PRs

2023-04-17 16:16 UTC, brandonspark commented on languages/scala/ast/AST_scala.ml
> +  | Opaque
same as above