Trim ids collected and remove remaining bytes at the end of them
semgrep/semgrep pull request #7812
Opened 2023-05-16 16:08 UTC by dinosaure

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

This PR trims `ids` collected by `Nosem.ml` and remove remaining bytes that are not a part of the `id`.

2023-05-17 09:06 UTC, aryx approved these changes

2023-05-17 14:25 UTC, aryx requested changes
Comments, deforest, and probably update the dune and dune-project files are required.

2023-05-17 14:25 UTC, aryx commented on src/reporting/Nosemgrep.ml
> +      Fmt.epr "%a\n%!" Fmt.(Dump.list string) ids;
Also probably better to remove those debugging instructions.

2023-05-17 15:32 UTC, hannesm commented
maybe a stupid question, but the `span` and unicode stuff seems to be like a big hammer... isn't it sufficient to get the rule_id as input, and use `String.index` with the space, tab, newline character -- and use the one that has the lowest index thereof for String.sub (or Str.first_chars)? when I understand this correctly, a rule id is terminated by any whitespace character (certainly, a question would be what to do with unicode whitespace characters, or non-printable characters (such as BEL))...

2023-05-17 15:34 UTC, aryx commented
yep, I agree with hannes, I wonder if there's a simpler way to solve it.

2023-05-19 08:58 UTC, dinosaure commented
I updated the PR according to your review and simplify a bit the process :+1:.

2023-05-19 09:48 UTC, merged