sophia/pa-2807 limit core autodetect to 16
semgrep/semgrep pull request #8028
Opened 2023-06-13 00:25 UTC by SophiaSR

Semgrep's memory usage grows linearly with the number of jobs. For now, limiting --jobs to 16 when autodetected. Otherwise, we can get into a situation where we detect a large number of underlying CPU cores, but the customer hasn't allocated a corresponding amount of memory.

Test Plan: For now tested by setting the max cores to 4, on a 10 core machine. Checked to see that this would run with 4 when no value given for jobs, but would run as 10 when set explicitly to 10 by user. 

PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-06-13 00:38 UTC, brandonspark commented
So *you* got the perf work.

2023-06-13 08:27 UTC, aryx requested changes
First PR!

Please can you also update osemgrep code, because this python code will at some point be removed. The relevant code is in src/osemgrep/cli_scan/Scan_CLI.ml, look for the call to get_cpu_count().

2023-06-13 08:27 UTC, aryx commented on cli/src/semgrep/engine.py
> +
Please add a comment in the code why we use a max of 16 (mostly copy what you put in your PR explanation in the code instead).

2023-06-13 16:16 UTC, SophiaSR commented
Added comments, and updated the osemgrep code as well. Not sure why the lint/pre-commit test is failing though, could someone take a look at that or point me in the right direction?

2023-06-13 16:19 UTC, aryx commented
hmm, I get the same error in another PR. Something is broken on develop probably.

2023-06-13 16:23 UTC, aryx commented
This is a user-facing change, so you should add an entry in changelog.d/pa-2807.changed

2023-06-13 16:23 UTC, aryx requested changes
Mostly good

2023-06-13 16:23 UTC, aryx commented on cli/src/semgrep/engine.py
> +        """Maxing out number of cores used to 16 if more not requested to not overload on large machines"""
I think in Python those docstring comments are usually written to explain the whole function and put
just after the ':'.
I think here you should use the '#' syntax for this kind of comment

2023-06-13 16:24 UTC, aryx commented
Hmm let me rerun the failing lint / pre-commit workflow.

2023-06-13 16:29 UTC, aryx commented
seems to work now.

2023-06-13 16:29 UTC, aryx commented
(Github action is quite flaky, just FYI, so it's not unusual we need to relaunch manually some failing jobs).

2023-06-13 17:05 UTC, aryx commented
This is a user-facing change, so you should add an entry in changelog.d/[pa-2807](https://linear.app/r2c/issue/PA-2807).changed

2023-06-13 17:07 UTC, SophiaSR commented
Added entry in changelog and updated to correct syntax

2023-06-13 17:13 UTC, aryx approved these changes

2023-06-13 18:44 UTC, emjin approved these changes
🚀

2023-06-13 18:45 UTC, merged

2023-06-30 15:28 UTC, IagoAbal commented on cli/src/semgrep/engine.py
> +        # Maxing out number of cores used to 16 if more not requested to not overload on large machines
If I didn't know what happened here, and I just found this comment, I would not know what "overload" means here.

2023-06-30 15:31 UTC, IagoAbal commented
I left a comment in Linear too, but this solution seems too ad-hoc. And I'm sure those using larger machines with the proper amount of memory will not realize that we have this limit, it's a bit like `interfile: true`, you know it's there but it's so easy to forget about it.

2023-06-30 15:32 UTC, IagoAbal commented on cli/src/semgrep/engine.py
> +        return min(16, self.get_cpu_count())
And we shouldn't be doing this silently, there should be warning being logged here IMO.