osemgrep: add comments and remove unneeded code
semgrep/semgrep pull request #8068
Opened 2023-06-16 10:28 UTC by hannesm

require a happy-eyeballs package which doesn't end up in the Azure (GitHub action) pre-commit issue

If that compiles fine, the right happy-eyeballs version is being used. And this paves the way for #7982

This reverts the timeout changes from #7984 (since they're not needed), and falls back to the defaults provided.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-06-19 08:06 UTC, hannesm commented
I rebased on top of develop and integrated the need for a more current base image (2023-06-16). this should now pass CI and solve the http timeout issue with osemgrep on github action / pre-commit.

2023-06-20 10:00 UTC, aryx commented
I think the mypy error is because you don't have the right semgrep-interfaces submodule. You probably did a mistake
when merging develop and forgot to git submodule update.
This PR should not change semgrep-interfaces.

2023-06-20 10:16 UTC, hannesm commented
sorry about that. I force-pushed and avoided the submodule change.

2023-06-20 11:47 UTC, aryx commented
I think we need to add a call to 'opam update' in scripts/oxs-setup-for-release.sh

2023-06-20 11:47 UTC, aryx commented
The CI failures are happening because we're running on self-hosted runner with probably old version of opam database.

2023-06-20 13:12 UTC, aryx requested changes
CI failures

2023-06-20 15:04 UTC, aryx approved these changes

2023-06-20 15:06 UTC, merged

2023-06-20 16:34 UTC, hannesm commented
thanks for merging!