Optimize `apk upgrade` in Dockerfile
semgrep/semgrep pull request #8130
Opened 2023-06-24 16:45 UTC by PeterDaveHello

Run `apk upgrade` with `--no-cache`, instead of an additional `apk update` to leave the cache in the Docker image.

PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-06-26 10:31 UTC, aryx reviewed
Can you add a comment about this --no-cache, and whether it still updates things
when a CVE is discovered.

2023-06-26 10:32 UTC, aryx requested changes
Need more explanations.
In 3 months we might don't remember what was it for (not all of us
are experts in Docker, or alpine linux)

2023-09-12 18:34 UTC, brendongo approved these changes

2023-09-13 15:56 UTC, PeterDaveHello commented
Hey @aryx,

The `--no-cache` just ensures we're getting the latest packages without saving the package index, making the image smaller. If Alpine's repos have updated packages due to CVEs, this will get them. Hope that clears things up!

2023-10-16 09:28 UTC, aryx commented
superseded by https://github.com/returntocorp/semgrep/pull/8989

2023-10-16 09:28 UTC, closed without merging

2023-10-16 12:58 UTC, PeterDaveHello commented
Didn't see the reason why to use another PR to replace this one, unless new contributors are not so welcome here ;(

2023-10-16 13:24 UTC, aryx commented
Sorry about that; it's just that this PR was still failing in pre-commit, was in conflict I think because based on a old version of Semgrep, and because it's made from a fork, it's a bit annoying to refine the PR in a fork. Cince it was a one-line change I thought it would be simpler to make another PR ...
But I'll add and tank you in the changelog.

2023-10-16 14:04 UTC, PeterDaveHello commented
okay, I got it ;)