Add .cjs and .mjs for javascript
semgrep/semgrep pull request #8274
Opened 2023-07-14 21:45 UTC by emjin

Pull in changes from semgrep-interfaces to have javascript parse .cjs and .mjs files.

Test plan: check parse stats via `stats/parsing-stats/run-lang` Also talk to @underyx

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-07-14 22:23 UTC, emjin commented
Here's confirmation that the update did change the extensions targeting:
```
➜  axios-axios git:(v1.x) semgrep --config p/default karma.conf.cjs
               
               
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file tracked by git with 1598 Code rules, 517 Pro rules:
                                                                                                                        
  Language      Rules   Files          Origin      Rules                                                                
 ─────────────────────────────        ───────────────────                                                               
  <multilang>      58       3          Community    1081                                                                
  js              242       1          Pro rules     517                                                                
                                                                                                                        
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00                                                                                                                        
                
                
┌──────────────┐
│ Scan Summary │
└──────────────┘

Ran 1598 rules on 1 file: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
  ```

2023-07-14 22:49 UTC, emjin commented
https://github.com/returntocorp/semgrep/pull/8255 will fix build issues

2023-07-18 06:59 UTC, aryx requested changes
Same, if someone modified directly lang.json this is wrong. We should modify generate.py now

2023-07-19 08:39 UTC, aryx approved these changes

2023-07-19 17:10 UTC, merged