fix(yaml): fix captures for sequences that contain mappings
semgrep/semgrep pull request #8388
Opened 2023-07-27 18:11 UTC by MichaHoffmann

fixes https://github.com/returntocorp/semgrep/issues/8226, pretty sure it also fixes https://github.com/returntocorp/semgrep/issues/7532 and https://github.com/returntocorp/semgrep/issues/5607

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-07-27 18:12 UTC, MichaHoffmann commented
before:
```
┌─────────────────┐
│ 4 Code Findings │
└─────────────────┘

    test.yaml
       foo
          example

            3┆ importantKey:
            4┆   prop1: true
            ⋮┆----------------------------------------
            9┆   importantKey:
           10┆     - idk: true
           11┆ # (BAD) this comment is still included in the match
            ⋮┆----------------------------------------
           15┆ importantKey:
           16┆   prop1: true
            ⋮┆----------------------------------------
           21┆ importantKey:
           22┆   - idk: true
           23┆ shouldNotInclude: true
```
after:
```
┌─────────────────┐
│ 4 Code Findings │
└─────────────────┘

    test.yaml
       foo
          example

            3┆ importantKey:
            4┆   prop1: true
            ⋮┆----------------------------------------
            9┆ importantKey:
           10┆   - idk: true
            ⋮┆----------------------------------------
           15┆ importantKey:
           16┆   prop1: true
            ⋮┆----------------------------------------
           21┆ importantKey:
           22┆   - idk: true
```

2023-07-27 18:32 UTC, emjin approved these changes
I'll add a test in another PR

2023-07-27 18:34 UTC, emjin requested changes
oops sorry one thing that needs to be changed

2023-07-27 18:34 UTC, emjin commented on src/parsing/yaml_to_generic.ml
> +        env.last_event <- Some (E.Mapping_end, pos');
```suggestion
        env.last_event <- Some (E.Sequence_end, pos');
```

2023-07-27 18:35 UTC, MichaHoffmann commented on src/parsing/yaml_to_generic.ml
> +        env.last_event <- Some (E.Mapping_end, pos');
oh, yeah good catch

2023-07-27 18:36 UTC, MichaHoffmann commented on src/parsing/yaml_to_generic.ml
> +        env.last_event <- Some (E.Mapping_end, pos');
done

2023-07-27 19:16 UTC, MichaHoffmann commented
failed test worked for me locally, might be flakiness
```
⬢[mhoffm@toolbox cli]$ pipenv run pytest --snapshot-update tests/e2e/test_ls.py::test_ls_multi
============================================================= test session starts =============================================================
platform linux -- Python 3.11.4, pytest-7.3.0, pluggy-1.0.0
rootdir: /var/home/mhoffm/git/semgrep/cli
configfile: pyproject.toml
plugins: freezegun-0.4.2, xdist-3.2.1, split-0.8.1, snapshot-0.9.0, rerunfailures-11.1.2, mock-3.10.0
collected 1 item

tests/e2e/test_ls.py .                                                                                                                  [100%]

============================================================== warnings summary ===============================================================
../../../.local/share/virtualenvs/cli-kEnraMvm/lib64/python3.11/site-packages/pytest_freezegun.py:17
../../../.local/share/virtualenvs/cli-kEnraMvm/lib64/python3.11/site-packages/pytest_freezegun.py:17
  /var/home/mhoffm/.local/share/virtualenvs/cli-kEnraMvm/lib64/python3.11/site-packages/pytest_freezegun.py:17: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):

tests/e2e/test_ls.py::test_ls_multi
  /var/home/mhoffm/git/semgrep/cli/src/semgrep/semgrep_core.py:21: DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
    with importlib.resources.path("semgrep.bin", exec_name) as path:

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================== 1 passed, 3 warnings in 4.66s ========================================================

```

2023-07-27 19:43 UTC, emjin approved these changes
Looks good now!

2023-07-27 21:22 UTC, aryx commented
Would be good to add test for this. Maybe the one used in the issues supposidely fixed by this PR.
When it comes to range, there's no easy way to use tests/patterns/ or tests/rules to show that it works. You can use
cli/tests/e2e/ and its snapshot based testing to dump the json for the range and assert they are right.

2023-07-28 04:01 UTC, emjin commented
@MichaHoffman I didn't end up getting time to add a test today, so if you're able to that would be great! Otherwise I can merge tomorrow and then follow up with a test

2023-07-28 05:47 UTC, MichaHoffmann commented
Added a basic snapshot test with the example from the issue.

2023-07-28 11:09 UTC, aryx commented
Need to fix precommit @MichaHoffmann 
need pre-commit install and then precommit run -a

2023-07-28 11:11 UTC, MichaHoffmann commented
> Need to fix precommit @MichaHoffmann need pre-commit install and then precommit run -a

fixed the formatting issue

2023-07-28 12:30 UTC, aryx commented
@ajbt200128 can you take a look at this PR? Seems like it causes some regressions with test_ls here: https://github.com/returntocorp/semgrep/actions/runs/5691293193/job/15426494310?pr=8388
```

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/e2e/test_ls.py::test_ls_multi - IndexError: list index out of range
= 1 failed, 1385 passed, 1 skipped, 2 xfailed, 5588 warnings in 173.56s (0:02:53) =
Error: Process completed with exit code 1.

```

2023-07-28 13:09 UTC, mhoffm-aiven commented
> @ajbt200128 can you take a look at this PR? Seems like it causes some regressions with test_ls here: https://github.com/returntocorp/semgrep/actions/runs/5691293193/job/15426494310?pr=8388
> 
> ```
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> =========================== short test summary info ============================
> FAILED tests/e2e/test_ls.py::test_ls_multi - IndexError: list index out of range
> = 1 failed, 1385 passed, 1 skipped, 2 xfailed, 5588 warnings in 173.56s (0:02:53) =
> Error: Process completed with exit code 1.
> ```

fwiw: that passed locally for me

2023-07-28 16:20 UTC, emjin commented
I think develop is having a problem with test_ls

2023-07-28 17:24 UTC, ajbt200128 commented
> I think develop is having a problem with test_ls

Yea none of these changes effect the LS

2023-07-28 18:06 UTC, ajbt200128 commented
Lol tests are passing except for benchmarks now. I think github is not having a good day

2023-07-28 18:26 UTC, merged

2023-07-28 18:38 UTC, emjin commented
Benchmarks fail because it tries to post a PR comment but doesn't have a token