feat(comparison): add in and not in for strings
semgrep/semgrep pull request #8406
Opened 2023-08-01 05:51 UTC by brandonspark

## What:
This PR makes it so that you can use `in` and `not in` in the Python sense, for strings.

## Why:
Feature request from community, see https://semgrep.slack.com/archives/C018NJRRCJ0/p1690862677954849

## How:
Just added the operators, and tests. Cleaned up some code while I was at it.

## Test plan:
`make test`

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-08-02 08:31 UTC, aryx requested changes

2023-08-02 08:31 UTC, aryx commented on src/engine/Eval_generic.ml
> +          Bool (Common2.string_match_substring (Str.regexp v1) v2)
So v1 is a regular expression? In python you can do ".*" in "abc" and it returns true? I just tried and it's not the case
so you probably want to use Str.regexp_string instead of Str.regexp.

2023-08-15 17:30 UTC, brandonspark commented on src/engine/Eval_generic.ml
> +          Bool (Common2.string_match_substring (Str.regexp v1) v2)
good catch! didn't realize the difference. fixed now.

2023-08-15 18:05 UTC, aryx approved these changes

2023-08-15 21:47 UTC, merged

2023-08-15 22:03 UTC, ievans commented
@brandonspark is there a corresponding update to the docs?

2023-08-15 22:04 UTC, brandonspark commented
@ievans There is not. I'll add it, thanks!