feat!: capture group bindings from metavariable-regex
semgrep/semgrep pull request #8510
Opened 2023-08-21 16:42 UTC by brandonspark

## What:
This PR makes it so that capture groups used in `metavariable-regex` regexes can now persist after the `metavariable-regex`.

## Why:
This is a big wanted feature, and will make our rule writing experience better.

## How:
Added logic which will factorize out the `metavariable-regex` stuff with `Xpattern_matcher_regexp`, and produce matches which will be passed up, in a similar way to `Metavariable_pattern`.

## Test plan:
`make test`

Closes PA-3011 PRO-120

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-08-23 08:59 UTC, aryx commented
Can this be done independently of the remove the $1, $2 ? I see the stacked-diff tag.

2023-08-23 16:59 UTC, brandonspark commented
@aryx we will incur a test failure if we do, because of a rule which is currently failing because of implicit metavariable unification for the reasons i mentioned in #8515

2023-09-07 09:48 UTC, aryx commented
Is this still a stacked diff?
Can you rebase on your other numeric_do_not_unify_mvar fix?

2023-09-07 20:35 UTC, brandonspark commented
@aryx this actually already is rebased on top of the other PR (see that the merge base is different). It's ready for review now, I think.

2023-09-08 11:57 UTC, aryx requested changes

2023-09-08 11:57 UTC, aryx commented on src/engine/Eval_generic.ml
> +  file : string;
Please use Fpath.t instead.

2023-09-08 11:57 UTC, aryx commented on src/engine/Eval_generic.ml
> +  file : string;
and also can you add a comment what this file refers to? Why do we need it?

2023-09-08 11:57 UTC, aryx commented on src/engine/Metavariable_regex.mli
> +  file:string ->
Please use Fpath.t in new code.

2023-09-08 11:57 UTC, aryx commented on src/engine/Metavariable_regex.mli
> +(* The first argument is the function
Is this comment still valid?
The first parameter (not argument)  is an environment, not a function ...

2023-09-11 20:20 UTC, aryx commented
failing in CI

2023-09-11 21:00 UTC, brandonspark commented
@aryx was just the snapshots, should be good now

2023-09-11 21:47 UTC, brandonspark commented
nvm there's more hold up

2023-09-16 00:30 UTC, brandonspark commented
@aryx I investigated and found that these errors are due to a lack of ported functionality to `osemgrep scan`. In particular, we are not properly deduplicating findings as the Python CLI does (see https://github.com/returntocorp/semgrep/blob/28820ed668db4eea3bb98144294ccd12418c1118/src/osemgrep/reporting/Cli_json_output.ml#L609).

This seems like a fair amount of code which is unrelated to the current feature, which simply surfaces an instance where this lack of deduplication is biting us. Would it be fair to simply remove this test from the list of `osempass` expected tests, and move on with merging (especially given that this is quite high priority)?

2023-09-16 07:57 UTC, aryx commented
ok remove the osempass, and maybe add a comment next to it with a TODO and link to this PR that introduced the regression, so another person can investigate it.

2023-09-18 22:10 UTC, akuhlens approved these changes
LGTM, @aryx feel free to follow up with @brandonspark with any further changes.

2023-09-18 22:27 UTC, akuhlens commented
Apparently I can't approve this if @aryx hasn't. I tried based off what I read as tacit approval. Sorry if I stepped on any toes.

2023-09-19 09:46 UTC, aryx approved these changes

2023-09-19 09:46 UTC, aryx commented on cli/tests/e2e/snapshots/test_check/test_metavariable_propagation_regex/results.json
> +          "$1": {
I thought we were actually considering the numeric metavar differently, and set unify_numeric_metavar to false.

2023-09-19 09:46 UTC, aryx commented on libs/commons/Regexp_engine.mli
>  val pcre_compile : string -> t
you could extend pcre_compile with a ?flags instead of defining a separate function

2023-09-19 09:46 UTC, aryx commented on src/engine/Eval_generic.ml
> +        `eval` can call the `Metavariable_regex` logic, whcih needs to produce
typo which

2023-09-19 09:47 UTC, merged