[feat:CLI] ℹ️ Add Nudge for Supply Chain Awareness
semgrep/semgrep pull request #8589
Opened 2023-08-30 22:41 UTC by zzeleznick

## Description
This PR adds a nudge to users who have not logged in and for those who haven't tried our **free** [supply chain dependency analysis feature](https://semgrep.dev/products/semgrep-supply-chain/).

### Demo 
<img width="1016" alt="Screenshot 2023-08-30 at 3 28 12 PM" src="https://github.com/returntocorp/semgrep/assets/5779832/cd47dd64-efc4-4a13-8caa-f697a1f4e837">

## Changes

### Adds
- messaging to improve awareness of our supply chain product
- section title for the progress bar
- emojis for attention callout to version update and no findings bottom banner

### Modifies
- spacing between section headers and tables 
- behavior of when the tables should display

<hr>

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-08-31 00:17 UTC, DrewDennison approved these changes

2023-08-31 02:30 UTC, bmahe approved these changes

2023-08-31 15:38 UTC, aryx requested changes
There are 172 test regressions, so let's take our time here before approving.

2023-08-31 15:43 UTC, aryx commented
To avoid the regressions, and to help for porting the code later to osemgrep, we could use a global feature flag like new_cli_UX,
that would be set to true by default, but could be changed to false when running our test infra, so this also gives
room for experimentation. Of course we don't want the code in it to be too big, because our e2e tests would actually not
be faithful to what is happening, but that would allow to experiment in a new UX in python without having to update all our tests and also having to update the OCaml code.

2023-09-01 14:52 UTC, aryx commented on cli/bin/pysemgrep
> +    os.environ["SEMGREP_NEW_CLI_UX"] =  f"{int(os.isatty(sys.stdout.fileno()))}"
so this does not return true when we invoke semgrep from pytest in rum_semgrep_in_tmp?

2023-09-04 09:58 UTC, aryx approved these changes

2023-09-04 09:59 UTC, merged