feat(dart): generic translation
semgrep/semgrep pull request #8704
Opened 2023-09-13 18:42 UTC by brandonspark

## What:
This PR implements the generic translation for the Dart programming language.

## Why:
We currently only have raw trees, meaning we get _very_ limited matching capabilities, but nowhere near the standard level of support Semgrep can have for a language.

## How:
Implemented the translation.

## Test plan:
TBD

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

2023-09-14 07:16 UTC, aryx requested changes
Please do not add semgrep-dart as-is; you should add it as a submodule instead

2023-09-15 09:16 UTC, aryx requested changes
nope, still not moved properly.
Please try to review your own PR to catch those kind of issues.

2023-09-15 09:16 UTC, aryx commented on languages/dart/generic/Parse_dart_tree_sitter.ml
> +(* Yoann Padioleau
put your name here brandon

2023-09-18 16:06 UTC, brandonspark commented
@aryx ok, NOW it should be good i think

2023-09-19 08:00 UTC, aryx approved these changes
3800 LOC ...
I think you forgot to modify Unit_engine.ml and add the maturity test for Dart.

2023-09-19 08:00 UTC, merged