add metrics for diff scans
semgrep/semgrep pull request #9061
Opened 2023-10-20 21:52 UTC by ihji

2023-10-22 08:23 UTC, aryx requested changes

2023-10-22 08:23 UTC, aryx commented on src/osemgrep/core/Metrics_.ml
> +let add_is_diff_scan (is_diff_scan : bool) =
I would remove those functions in osemgrep. I know pysemgrep is doing it, but I think it's stupid,
It just forces us to add one function for every field ... just access the field directly
at the call site.
I would use a function if we do something complicated with the argument, for example add_errors does the preprocessing on the errors to fit in the metrics data structure, but here we don't do anything.

2023-10-23 16:07 UTC, ihji commented on src/osemgrep/core/Metrics_.ml
> +let add_is_diff_scan (is_diff_scan : bool) =
makes sense. removed the helper functions and updated the field directly.

2023-10-23 16:49 UTC, aryx approved these changes

2023-10-23 16:49 UTC, merged