fix(ls): gracefully handle unauthorized token
semgrep/semgrep pull request #9135
Opened 2023-11-01 22:56 UTC by brandonspark

## What:
This PR makes it so the language server does not crash upon pulling rules using an invalid token, and instead displays a helpful error message.

## Why:
It's kind of a crappy user experience to have the LS crash entirely.

## How:
I refactored a lot of the possibly-erring networking functions to instead return `Result`s. To induce minimal labor at use sites, I also included an `Unsafe` module within the `Rule_fetching` file, which contains the exception-raising variants.

This gives full power to the consumers of this API to either handle the errors or not.

Unfortunately, the code which triggers the rule fetching occurs in `Session.ml`, which cannot use `RPC_server.notify_send_message` because of module dependencies. I ended up just including the `RPC_server.notify_send_message` function into the `Session.t` type, so that it would be available.

## Alternatives considered:
The easiest way to do this would have simply been to use exception handling, but I do not like exception handling and I was afraid this would lead to hard-to-understand code.

I figured that it would be better to have these networking functions be clear about their exception-raising nature, and to embed that into the `result` type.

We could have also used some global state (like a list of messages or something) which would be depleted as messages came in, in the main `RPC_server` loop, instead of embedding `notify_send_message` into `Session.t`, but I also wanted to avoid global state.

2023-11-02 11:23 UTC, aryx reviewed
This Lwt refactoring is ugly. We really need to switch to EIO ASAP so
we can use exception and avoid this LWTification and RESULTification.
I want my exception back!

2023-11-02 15:26 UTC, brandonspark commented
@aryx Yeah, I agree, it's ugly, but my sense of when it's appropriate to use exceptions as `goto`s is still pretty underdeveloped. In most cases, I try to avoid them at all costs. I figured that this is a bit of maintenance in the moment, but should be low maintenance going forward.

2023-11-02 16:00 UTC, aryx commented
Not a fan of lwt, not a fan of the result type. I like exceptions to report errors.

2023-11-02 16:12 UTC, brandonspark commented
@aryx I agree, but we can't stop execution, right? We need the LS to keep going, and we need the exception to actually translate into a call to `notify_send_message`.

2023-11-02 16:13 UTC, brandonspark commented
I also think the result type is clearer, because callers aren't necessarily aware of the fact that this call to `Rule_fetching` may actually result in an exception. That's what caused this behavior in the first place.

2023-11-02 17:35 UTC, ajbt200128 requested changes
The better way to do this would be to use (or use as a reference) `get_deployment_from_token_async` in osemgrep/networking/Semgrep_App.ml. That demonstrates a good way to verify that a login token is working. I'd try doing that on startup, and if it's invalid, just delete the token and prompt them to login again.

This way we can be explicit about knowing if the user is logged in, and we can just nudge them to login again.
You can use that function, but it'd be preferable to add a `verify_token_async` to semgrep_login or semgrep_app, that maybe wraps this function into a bool

2023-11-03 09:11 UTC, aryx commented
totally agree with @ajbt200128 . Better to check early and raise early.
That way you don't need all this error handling and lwt-ificication and result-ification.

2023-11-03 21:17 UTC, closed without merging

2023-11-03 21:22 UTC, brandonspark commented
for some reason it closed my branch, check https://github.com/semgrep/semgrep/pull/9157 for the new one @aryx @ajbt200128