chore: linecol to bytepos
semgrep/semgrep pull request #9223
Opened 2023-11-10 22:04 UTC by brandonspark

## What:
This PR refactors the `bytepos_to_linecol_fun` type into a `pos_info` type, which contains both a `bytepos_to_linecol_fun` and a `linecol_to_bytepos_fun`.

## Why:
I needed the linecol to bytepos function, and it seemed easiest to piggyback off of the `bytepos_to_linecol_fun` logic, and compute both at the same time.

## How:
We use the previous PR https://github.com/semgrep/semgrep/pull/9222 to quickly search for the proper line/col, by binary searching over all the byte positions previously computed (and their associated line/cols).

It currently raises an exception on being given an invalid line/col.

## Test plan:
TODO

2023-11-12 09:08 UTC, aryx requested changes

2023-11-12 09:08 UTC, aryx commented on libs/lib_parsing/Pos.ml
> +type pos_info = {
maybe type bytepos_linecol_converters ?

2023-11-12 09:08 UTC, aryx commented on libs/lib_parsing/Pos.ml
> +let complete_position filename pos_info (x : t) =
maybe converters instead of pos_info ?

2023-11-12 09:08 UTC, aryx commented on libs/lib_parsing/Pos.mli
> +   If the (line, column) is out of range, an exception will be raised.
which exception?

2023-11-13 21:09 UTC, aryx approved these changes

2023-11-13 21:09 UTC, aryx commented on languages/yaml/generic/yaml_to_generic.ml
> +  let charpos_to_pos =
rename charpos to bytepos here (to be consistent).

2023-11-13 21:09 UTC, aryx commented on languages/yaml/generic/yaml_to_generic.ml
> +  let charpos_to_pos =
and also because we operate at the bytepos level, not (unicode) character level.

2023-11-13 22:03 UTC, merged

2023-11-13 22:11 UTC, kopecs commented
Formatting?