[DRAFT](osemgrep): port `semgrep publish`
semgrep/semgrep pull request #9278
Opened 2023-11-16 21:52 UTC by brandonspark

TODO

Currently, it seems we are blocked on https://github.com/semgrep/semgrep/pull/9266, since we need to mock the login function in order to port `test_publish.py`.

2023-11-20 08:48 UTC, aryx commented
9266 is merged

2023-11-21 22:18 UTC, aryx reviewed
There are lots of things that seem completely unrelated to semgrep publish
but looks like refactoring/cleanup.
Those look useful, but please make a separate PR for that, so we can merge that quickly.

2023-11-22 19:01 UTC, aryx commented
I've merged your other PR about subcommand="...", you can merge develop

2023-11-22 20:00 UTC, aryx requested changes
Looks pretty good.
Would be good to add comments to actually explain what this publish
thing is doing and what are the subtle things.

2023-11-22 20:00 UTC, aryx commented on src/osemgrep/cli_publish/Publish_CLI.ml
> +   LATER: we could actually define this structure in ATD, so people could
please do not copy comments from other files; just copy the code, or put the comment
if it helps understand the code, but no need for TODO/LESS/LATER todo comments.

2023-11-22 20:00 UTC, aryx commented on src/osemgrep/cli_publish/Publish_CLI.ml
> +  registry_id : string option;
need to add common: CLI_common.conf;

so we can use --debug, --experimental, etc. with this subcommand too.

2023-11-22 20:00 UTC, aryx commented on src/osemgrep/cli_publish/Publish_CLI.ml
> +  target : string;
target is used consistently in semgrep to mean target file, so probably better to rename this field.
Is the string correspond to a filename? A rule_id? (in which case please use Rule_ID.t)

2023-11-22 20:00 UTC, aryx commented on src/osemgrep/cli_publish/Publish_subcommand.ml
> +   Parse a semgrep-publish command, execute it and exit.
Maybe you can give some explanations of what semgrep publish is doing.
Most of us are not familiar with this command, so can be useful to explain it a bit.
This would help understand the code.

2023-11-22 20:00 UTC, aryx commented on src/osemgrep/cli_publish/Publish_subcommand.ml
> +(* old: was a thing where we split up the file exts into a suffix list, then
@hannesm is porting test.py in https://github.com/semgrep/semgrep/pull/9247
maybe you can define a common file to have those constants and helpers
shared between commands.
maybe put it in src/osemgrep/core/Rule_tests.ml or something.

2023-11-22 20:00 UTC, aryx commented on src/osemgrep/cli_publish/Publish_subcommand.ml
> +          [
would be good to define the schema in semgrep_output_v1.atd instead.

2023-11-22 20:00 UTC, aryx commented on src/osemgrep/cli_publish/Publish_subcommand.ml
> +      (* THINK: is this how we get the semgrep URL? *)
please move this code in Semgrep_App.ml

2023-11-22 20:00 UTC, aryx commented on src/osemgrep/cli_publish/Test_publish_subcommand.ml
> + * test_login.py to test osemgrep because of the use of mocking
don't copy comments, or if you do at least update the comment, here s/test_login.py/test_publish.py

2023-11-22 23:15 UTC, brandonspark commented on src/osemgrep/cli_publish/Publish_subcommand.ml
> +          [
I left a LATER, I think I will leave this to a future PR so this one can get in for now

2023-11-23 13:58 UTC, aryx approved these changes

2023-11-23 13:58 UTC, merged