Experiment: using capabilities for the semgrep codebase
semgrep/semgrep pull request #9350
Opened 2023-11-29 22:32 UTC by aryx

See the talk I'll make to the PA/SR talk for the motivations and explanations of this work.

2023-11-30 20:33 UTC, mjambon requested changes
I approve the new modules that end with an underscore (`List_` etc.) but not the code related to capabilities in its current design. I'll give details on this on Slack or in person.

2023-12-02 00:41 UTC, emjin commented
Do you have a sense of what the slowdowns are coming from?

2023-12-03 14:25 UTC, aryx commented
nope, dunno why we regress, which is why I'm merging parts of this PR piece by piece.
I'm down to +770-650 for the PR so this becomes easier to debug.

2023-12-04 16:02 UTC, aryx commented on src/main/dune
> + ;XXX(modes native byte)
@emjin mode natives strike again!
I commented it while experimenting and forgot about it.

2023-12-05 10:12 UTC, merged