fix: Add `--` to git diff command
semgrep/semgrep pull request #9775
Opened 2024-02-14 19:53 UTC by bafulton

## Problem

Some repositories contain a file in the root dir with the same name as that of the main branch. When this is the case, running a git diff against the main branch results in an error.

```
❯ ls
main
[...]

❯ git symbolic-ref HEAD --short
main

❯ git diff main
fatal: ambiguous argument 'main': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

## Solution

Append a `--` to the command as recommended by git. This clarifies we're interested in diffing the branch, not the file.

```
❯ git diff main --
```

Adding this parameter has no effect for repositories without a root file with the same name as the main branch, so we can safely add it to our command across the board.

2024-02-14 19:58 UTC, bafulton commented on cli/src/semgrep/git.py
> +            "--",  # end of options, start of file paths
I've confirmed we can append other flags after this (eg, the `--merge-base` flag below. This param just needs to follow the branch name.

2024-02-14 19:59 UTC, bafulton commented on cli/src/semgrep/git.py
> +            "--",  # end of options, start of file paths
I've confirmed we can append other flags after this (eg, the `--merge-base` flag below. This param just needs to follow the branch name param (`self._base_commit`).

2024-02-14 20:13 UTC, ievans commented
@bafulton a test case would be great as well as I assume this code is / already moves to ocaml

2024-02-15 16:06 UTC, aryx requested changes, later dismissed
yep, what isaac said, please add an e2e tests, which will then lead you to also improve
the osemgrep code.

2024-02-15 16:07 UTC, aryx commented
If modifying osemgrep and its OCaml code is too complicated, just add the e2e tests and we can push on your branch to fix osemgrep ourselves.

2024-02-16 19:13 UTC, bafulton commented on cli/tests/e2e/test_baseline.py
> +    run_sentinel_scan(base_commit="main")
I've confirmed this raises an exception on `develop`.

2024-02-16 20:48 UTC, aryx commented on cli/tests/e2e/test_baseline.py
> +    run_sentinel_scan(base_commit="main")
great

2024-02-16 20:48 UTC, aryx commented on cli/tests/e2e/test_baseline.py
> +def test_conflicting_file_and_main_branch_names(git_tmp_path, snapshot):
@ihji do you know why this test seems to pass also in osemgrep?
Ben didn't fix osemgrep code like pysemgrep but CI does not report any test failure ...
Does osemgrep and Git_wrapper.ml already handle correctly branch names that can be also files?

2024-02-20 19:03 UTC, cgdolan approved these changes
LGTM, thanks! Approving so we can get this change into pysemgrep ASAP since that's what ZCS is currently using and where we're seeing the most errors. Analysis team agreed to handle the osemgrep changes.

2024-02-20 19:07 UTC, cgdolan commented on cli/tests/e2e/test_baseline.py
> +def test_conflicting_file_and_main_branch_names(git_tmp_path, snapshot):
Closing this thread out to unblock the fix for pysemgrep. Let's continue the discussion for the osemgrep changes in a follow up.

2024-02-20 19:08 UTC, merged